第3回pymee資料
pymee/studygroup pull request #20
Opened 2018-11-22 13:40 UTC by kotarouikeda

001ReviewList.py：前回の復習(リスト)
002ReviewDic.py：前回の復習(辞書型)
011For.py：for文(例文)
012ForRange.py：for文(例題/Range)
013ForSample.py：for文(サンプルプログラム)
021FileIo.py：ファイルIO(例文)
022FileIoSample.py：ファイルIO(サンプルプログラム)
031Exception.py：例外(例文)
032FileNotFoundException.py：例外(サンプルプログラム)
041Summary.py：まとめ
daikiti.txt：まとめ用テキスト
kiti.txt：まとめ用テキスト
kyo.txt：まとめ用テキスト
outputSample.txt：例外用テキスト
pymee3.md：勉強会資料

051Bonus.py：対象外(資料内で使っていません、githubのURLへ誘導する形にしました)

2018-11-23 13:25 UTC, R-Horio requested changes

2018-11-23 13:25 UTC, R-Horio commented on 3rd/pymee3.md
> +```
```suggestion
```python
```
意図的にかもしれないですが、```の後にpythonとつけるとGitHubのMarkdownの仕様でコードにカラーがついて可読性が高くなるかと思います。

2018-11-23 13:50 UTC, R-Horio commented on 3rd/pymee3.md
> +```
資料のコードの部分と出力の部分・参照するファイルの部分が同じ書き方になっているのでMarkdownで分類すると見やすくなるかもしれません。
下記はmarkdownでそれらしく使えそうなのを選んでみた例です。
この辺は好みも分かれると思うのでいろいろな人の意見を聞きたいです。

* コード部分
```python
print("hello, world")
```

* 実行結果
> \>> 大吉 すべてよし
> \>> 運勢: xxxx

* コマンドの実行
Mac/Linux: `python 00_sample.py`
Windows: `py 00_sample.py`

* 参照するファイル
> 参照ファイル：00_sample.py

2018-11-26 00:44 UTC, JinKanai commented on 3rd/pymee3.md
> +```
全面的に賛成

2018-11-26 00:45 UTC, JinKanai commented on 3rd/pymee3.md
> +```
```
 ```python
```
↑これは、marpが解釈してくれれば（エラーにならなければ）採用ということで！

2018-11-28 08:18 UTC, kotarouikeda commented on 3rd/pymee3.md
> +```
つくづくgithubは面白い機能備えてますね・・・
折角ですし、やってみます！Markdownに関しては分かる部分をつぎはぎでやってるレベルなので、このようなテクニックやアイデア等あればガンガン突っ込んで下さい！

2018-11-29 16:06 UTC, sanoP1man commented on 3rd/pymee3.md
> ++ 関数
```suggestion
+ 関数(print()など)
```
ここの`関数`は、組み込み関数のprintを使うという意味ですよね。（違ったらすみません)
`関数`と書くと`関数の定義`に間違えて認識するかなと思いました。

2018-11-29 16:06 UTC, sanoP1man commented on 3rd/pymee3.md
> +```
`「```python」`に変更して問題なしです:exclamation: 
marpでの表示とpdf出力を実行し、両方とのエラーがでないことを確認しました。
コードの可読性が上がっていいと思います。

2018-11-29 16:07 UTC, sanoP1man commented on 3rd/pymee3.md
> +#! python3
#8 でシェバンは今回使用しないことになったので、使用しない方がいいと思います〜
シェバンの説明していないので、これはなんだ？のところから始まると思うので。

2018-11-29 16:27 UTC, sanoP1man commented on 3rd/pymee3.md
> +#下記の例文だと0～9の値が入ったリストが作られる。
range()で作成したオブジェクトはリスト型ではなくてrange型だったので、「リストが作れる」だと正確じゃないと思います。
説明方法難しいですね、、、いい説明私も考えます。

色々調べた結果です。
+ python2とpython3でrange()の動作が異なる
python2だとrange()ではリストが生成され、python3だとリストではなくオブジェクトを作成しメモリを確保せずに計算しながら数字を出力しているようです。[参考リンク](http://komaken.me/blog/2013/05/16/python2-x系でfor文でrangeを使う際に気をつけたいこと/)

*  下記は、実際にtype()で型をみた結果です。
```
>>> range_var = range(10)
>>> type(range_var)
<class 'range'>
>>> 
>>> print(range_var)
range(0, 10)
>>> 
>>> list_var = [0,1,2,3]
>>> type(list_var)
<class 'list'>
>>> 
>>> print(list_var)
[0, 1, 2, 3]
```

2018-11-29 16:30 UTC, sanoP1man commented on 3rd/pymee3.md
> +    print (o);
```suggestion
    print (o, end='');
```
末尾に改行が入ってしまうので、print()でオプションの指定が必要です。

2018-11-29 16:32 UTC, sanoP1man commented on 3rd/pymee3.md
> +
あとで入れ込む予定だったらすみません、、、
おみくじプログラムもテキストファイルから読み込んで使用できるように改良するのはどうですか？

2018-11-29 16:34 UTC, sanoP1man commented on 3rd/src/021FileIo.py
> +    print (o);
```suggestion
    print (o, end='');
```
改行が入ってしまうので、endを設定する必要だと思います。

2018-11-29 16:38 UTC, sanoP1man requested changes
レビュー途中ですが、修正依頼を出したのでRequest changesでお願いします！

2018-11-30 06:01 UTC, uranos0601 commented on 3rd/pymee3.md
> +# 例外
おみくじプログラムにファイル読み込みを組み込むのであれば、
エラーも組み込めたらもっとデラックスなおみくじプログラムになるかと！

2018-11-30 16:42 UTC, sanoP1man commented on 3rd/pymee3.md
> +
そもそもforの書き方について、下記の３つも重要な点だと思うので説明した方がいいと思います。
1.  取得した値を変数に格納しfor節で利用可能なこと
1.  インデントで字下げした部分がfor節になること
1.  in の後ろに記載できるのは、リストや辞書、文字列といったものを利用可能
1については、エラーが起こるプログラム(forで定義した変数やforの中で定義した変数をforの外から呼んでいる)と、そのプログラムを実行した結果を記載した方がイメージが湧きやすいと思います。

2018-11-30 16:46 UTC, sanoP1man commented on 3rd/pymee3.md
> +記載した通り、for文はリストから値を取得する事が前提の作りになっています。
```suggestion
for文はリストにある値を全て出力する事が前提の作りになっています。
```
for文はリストしか利用できないように思われるかもしれないので、上記のように変更した方がいいと思いました。
リストではイテレータに対応しているオブジェクト(リスト、辞書、文字列など)であれば利用可能なので。

2018-11-30 16:48 UTC, sanoP1man commented on 3rd/pymee3.md
> +
「omikujiというリストの中身を全て表示するプログラムを作ります！」という様な形でどういうプログラムを作るか先に説明した方いいと思いました。(口頭で説明予定だったら大丈夫です！）

2018-11-30 16:49 UTC, sanoP1man commented on 3rd/pymee3.md
> +
open()の引数部分について説明を入れた方がいいと思いました。

2018-11-30 16:50 UTC, sanoP1man commented on 3rd/pymee3.md
> +【事前準備】
サンプルプログラムで何をするか説明してから実際にプログラムを作ってもらった方が理解が深まるかなと思いました。(説明予定だったらすみません。)

2018-12-01 06:36 UTC, JinKanai commented on 3rd/pymee3.md
> +# 例外
エラーを組み込むとは、具体的にはどんなことです？

2018-12-01 09:59 UTC, sanoP1man commented on 3rd/pymee3.md
> +
他にも下記のような読み込みの方法があるので、使い方を紹介した方がいいかなと思いました。

+ 特定の文字数だけ読み込む場合(下記は３文字づつ)
> \>>> output = open("outputSample.txt", "r", encoding="utf-8")
> \>>> output.read(3)
> '待人：'
> \>>> 
> \>>> output.read(3)
> '辛抱強'
+ １行づつ読み込む場合
> \>>> output = open("outputSample.txt", "r", encoding="utf-8")
> \>>> output.readline()
> '待人：辛抱強く待つべし\n'
> \>>> output.readline()
> '失物：足元にあり\n'

+ 次の読み込み開始の位置を覚えており、再度output.read()やoutput.readline()を実行すると以前の読み込み開始位置から出力される。
+ ファイルの最後まで行くと空欄の''が出力される。
+ ファイルの読み込み開始位置はoutput.tell()で確認可能。
+ output.seek(0,0)でファイルの先頭へ読み込み開始位置を戻すことができる。

2018-12-01 09:59 UTC, sanoP1man commented on 3rd/pymee3.md
> +
ここでエラーには構文エラーと例外の２種類があり、フォローできるのは例外のみであることは伝えた方がいいと思います。
合わせて、エラー出力時には  ^で個所、lineXで該当行数表していることも伝えて参加者自身がデバッグの糸口を見つけれるようにしたらどうですか〜

+ エラー出力時(構文エラー)
```
$ python3 SyntaxError_sample.py 
  File "SyntaxError_sample.py", line 3
    print(test))
               ^
SyntaxError: invalid syntax
```

2018-12-01 10:00 UTC, sanoP1man commented on 3rd/pymee3.md
> +#基本的に全部でいい。
「基本的に全部でいい」だとコードを全て囲んでしまうことになりそうなので、「エラーが発生しそうな個所を全てtry:〜except:で囲む」の方がいいと思います。

2018-12-01 10:01 UTC, sanoP1man commented on 3rd/pymee3.md
> +
下記２点も追加した方がいいと思います。
+ elseで例外が発生しなかった時の処理を指定可能なこと
+ finallyで例外発生時でも正常終了時でも実行する処理が指定可能なこと
```
else:
  print('例外が発生しない場合実行される処理')
finally:
 print('例外が発生しても、しなくても実行される処理')
```

2018-12-01 10:07 UTC, sanoP1man commented on 3rd/pymee3.md
> +
繰り返し処理第２弾とファイルの書き込みでいいと思います！
細かいことは決まっていないので、ざっくりとした内容を伝える形で問題ないと思います。

2018-12-01 10:43 UTC, sanoP1man commented on 3rd/src/041Summary.py
> +
exceptはopen直下につけた方がいいと思います〜
理由は、exceptで全てを囲んでしまうと補足する予定ではなかったエラー(open()以外で発生したもの)がわからなくなるのと、open()のファイル名以外はプログラムファイルの位置が変わっても変わらない部分なのでエラーを補足する必要がないように思います。

2018-12-01 10:44 UTC, sanoP1man commented on 3rd/src/041Summary.py
> +
＃14-#26を output = random.choice([daikiti, kiti, kyo])  でまとめれるかなと思ったのですが、辞書やリストを復習するためにあえて使用しているという形だったりします？
意図があるのであれば、このままで大丈夫だと思います！

2018-12-01 10:44 UTC, sanoP1man commented on 3rd/src/041Summary.py
> +        print (o);
```suggestion
        print (o, end='');
```
改行が入ってしまうのでend=''が必要です〜
end=''を追加する場合、forの外にprint('\n')を入れた方が見やすくなります。

2018-12-01 10:44 UTC, sanoP1man commented on 3rd/src/041Summary.py
> +    output.close()
```suggestion
    daikiti.close()
    kiti.close()
    Kyo.close()
```
選択されてないファイルオブジェクトがcloseされていないので３つともクローズするように修正が必要です。

2018-12-01 10:46 UTC, sanoP1man commented on 3rd/pymee3.md
> +
最終的には041Summary.pyを作ってもらう予定だったりします？（ファイル全部見てなくてすみません。。。)

2018-12-01 10:51 UTC, sanoP1man commented on 3rd/src/031Exception.py
> +        output.close()
```suggestion
    output.close()
```
for節の中にclose()があるので外に出した方がいいと思います。
その前に例外が補足されるので処理が行われませんが。。。

2018-12-01 10:51 UTC, sanoP1man commented on 3rd/src/032FileNotFoundException.py
> +
ここもforの外に出した方がいいですね〜

2018-12-01 11:05 UTC, sanoP1man commented on 3rd/pymee3.md
> +        output.close()
```suggestion
     output.close()
```
forの外にした方がいいです〜

2018-12-01 11:07 UTC, sanoP1man commented on 3rd/pymee3.md
> +```
041Summary.pyにも記載したので繰り返しになってしまいますが、、、
exceptはopen()の下の方がいいと思います〜

2018-12-01 11:09 UTC, sanoP1man commented
レビュー終わりました。色々とコメント入れたので大変ですが確認お願いします。。。
コメントにわかりずらい箇所があれば遠慮なく聞いて下さい！

2018-12-01 17:28 UTC, R-Horio commented on 3rd/pymee3.md
> +
1 の取得した値を変数に格納というのはfor i in xxx: のiのことでしょうか？
`for _ in range(10):` => 10回繰り返したいが値の代入の必要はない（余計なメモリを食わない）
`for num, value in enumerate([10, 20, 30]):` => リストの中身を取り出しつつindexをつける
などの使い方もされるときはありますが今回は一般的な使い方を想定した説明でしょうか

2018-12-01 17:44 UTC, R-Horio commented on 3rd/pymee3.md
> +
業務での使用を想定するのであればファイルIOは基本的に以下のような使い方にするのがいいと思います。withから出た際にcloseされるのでクローズし忘れもなく見通しも良くなると思います。
```python
with open("outputSample.txt", "r", encoding="utf-8") as f:
    print(f.read())
```

2018-12-02 03:14 UTC, sanoP1man commented on 3rd/pymee3.md
> +
コメントありがとうございます～
1の「取得した値」はfor i in xxx: の「i」のことです。
今回はリストの中身をすべて取り出す使い方を想定してました。

下記はrangeを使用したforのところで紹介したらよさそうですね。
詰め込みすぎかな。。。

> `for _ in range(10): `=> 10回繰り返したいが値の代入の必要はない（余計なメモリを食わない）
> `for num, value in enumerate([10, 20, 30]): `=> リストの中身を取り出しつつindexをつける

2018-12-02 04:03 UTC, R-Horio approved these changes

2018-12-02 08:31 UTC, JinKanai requested changes
最近あらゆるものを舐めまくる子供の監視をしながらなんとかレビューした。ソースコードのレビューは他の人にまかせたｗ
ごめんなさい、ChangeRequestです

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +
@sanoP1man 
プログラムをテキストファイルから読み込むってどういうこと？

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +
Withを使ってないときのファイフハンドルはfinallyでクローズするのが必須なので含めましょう

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +【今回の講義で利用する知識】
細かい話ではありますが、markdownを使っているので、各項目のタイトルになる部分には【】などを使わずに#で表現しましょう！
強調する場合に使うのはありと思います

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> ++ 関数
今回、defで関数を作ることに触れなないので、関数という項目自体なくてもいい気がします

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +# omikujiという名前の変数に辞書型で一組ずつ「キー：値」の形で格納している。
鍵と書いてあったりキーとあったりするので、表記を統一したほうがよいです。
これ初心者向けの勉強会では結構大事です。
画像に鍵とあるので、資料でも鍵にしたほうがいいですかね

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +
時間が足りればやってもいいと思います。
こういう機能があります！っていう紹介は、実際に必要になるまで頭に入らないことが多いので、enumerateは私はやんなくてもいいと思う

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +
pythonのforってイテレータオブジェクトから値取り出すだけだっていう説明だけでもいい気がするんだよね・・
・レガシーな言語だとforって配列のポインタをカウントするのに使うけど、javaの拡張forとかもイテレータ的なものからの取り出しだし
わしpythonでコード書いて、rangeでforて書いたことないわ。。

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +記載した通り、for文はリストから値を取得する事が前提の作りになっています。
リスト、タプル、辞書、文字列などから一個づつ値を取り出せます！
で今回はいい気がする。
イテレータとか言ったら混乱するで

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +【例文(for文+Range関数)】
このページ、一枚に収まってないので分割お願いします！

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +#下記の例文だと0～9の値が入ったリストが作られる。
rangeでのforは優先度下げていいと思います。
pythonでrangeでforってやったことないんだけど、実は必要だったりするの？？？
pythonって古典的な配列がない（あるのかな？使ったことないから知らない）ので、予め範囲を指定するような使い方って効率悪いからやらないんだよね。イテレータオブジェクトの中身がなくなるまで全部出す！ってやったほうが効率いいので、rangeの説明は要らない気がするなあ・・・・
あ、もちろん時間があればOK

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +## サンプルプログラムを作ってみましょう(for文)
ここもページ溢れてる・・・ので、分割かな！

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +※今後「IO」と言う単語が出てきますが、「INPUT/OUTPUT」の略称で「入力(読み込み)/出力(表示)」を指しています。
おれがおっさんだからかもしれんが、「I/O」のほうがしっくりきますｗ

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +【例文(ファイルIO)】
このページも分割ですかね

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +for o in output:
こまけー話をしますが、変数名、
output -> contents　もしくは file_no_zenbu_no_gyou
o -> line もしくは　gyou
とか、具体的な名前をつけた方が初心者向けになるかなーと思ったり。
file_no_zenbu_no_gyouから１行づつgyouをforで取り出してるんだな〜とイメージしやすいかと。

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +
うーむ
個人的にはopne&closeで今回はよいかと。
ファイルハンドルをopenして、明示的にcloseするのが見えたほうがわかりやすいです。

具体的な話ですが、プログラム全体に渡ってファイルに書き込みさせたい場合、コンストラクタでopenしてインスタンスにハンドラをもたせて、デストラクタでそのハンドルをcloseすることとか私よくやったりします
読み込むときはwithでもいいんですんけどね。withだと、ファイルハンドルを持つというイメージが掴みにくいかなと思ったりしました

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +# 例外
例外処理
のほうが、項目名としては適切かな

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +
例外処理のまえにエラーについて説明する箇所を設けたほうがいいっすね
時間あるかな。。。

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +#基本的に全部でいい。
そっすね。tryするのは、エラーが起こる可能性が非常に高い部分のみに限定しないと、どこで例外が起きたかの捕捉が難しくなりますね

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +先述のtry～exceptを記載する事で、万が一処理に失敗した場合のフォロー処理を行う事ができます。
事前に読ませる資料であればこれでOKですが、口頭で説明しながら文章を目で追うのは参加者には結構きついです。
要点を箇条書きにしたほうがよいかと思います。

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +サンプルプログラムではexcept句がさらに2か所に分かれています。
ここも要点を箇条書きですかね

2018-12-02 08:31 UTC, JinKanai commented on 3rd/pymee3.md
> +
業務で絶対に必要になるのは
- jsonかCSV
- webのハンドリング
- ロギング
- テストコード
- オブジェクト指向的なとこ（フレームワーク使うのに必須）
だけど、次回でできるか。。な。。。

2018-12-02 13:56 UTC, nakayama-akio commented on 3rd/pymee3.md
> +
口頭説明の予定だと思いますが、
open関数の書式や動きについて説明があれば
ファイルの取り扱いがイメージしやすいかなと思いました。
※modeやEncodingの説明や、FileObjectをリストや辞書で
　使用したイメージ図(箱の絵など)を口頭補足できれば、
　受講者もイメージしやすいかなと思いました。

2018-12-02 15:52 UTC, R-Horio commented on 3rd/pymee3.md
> +
確かに今回の場合ではopen&closeでも全然問題はないですね。
with openはそのうち触れる程度にやるのがいいくらいですかね？

2018-12-02 16:13 UTC, R-Horio commented on 3rd/pymee3.md
> +
僕もpythonでrangeを使ったforはほとんど書いたことないです。固定回数繰り返したいプログラムはなかなか珍しいですし。。。

今回はイテレータから値取り出し だけにしたほうが初めての人には混乱せずに済みそうですね。

2018-12-02 18:49 UTC, juke211 requested changes

2018-12-02 18:49 UTC, juke211 commented on 3rd/pymee3.md
> +![](./img/list.png)
コードと図で要素のindexが異なっているのが気になりました。
どちらかに揃えたほうがいいと思います。

2018-12-02 21:25 UTC, JinKanai commented on 3rd/pymee3.md
> +
あとデバッグもですね

2018-12-03 00:48 UTC, HIROSEKAN commented on 3rd/pymee3.md
> +
私も普段はwith openを使ってますが、おっしゃる通り今回の説明はopen&closeがいいかと思います。
もし説明するなら、「with open という書き方もあるよ～気になる人は見てみてください」というレベルで、さらっとスライド1枚挿むくらいでよいかと思います。

2018-12-03 00:49 UTC, JinKanai commented on 3rd/pymee3.md
> +
実はwith open っていうのがあり・・という紹介を、時間があったらやりましょうかね！

2018-12-03 00:50 UTC, JinKanai commented on 3rd/pymee3.md
> +
上の方で、rangeのforって必要なの？みたいなこと書きましたが、何かを100万回計算したいとか、計算用途ならあるんでしょうね、きっと。
私は基本文字ばっかり扱っているので、要素がなくなるまで処理、っていうくらいしかforを使ったことがなく。

2018-12-03 01:35 UTC, HIROSEKAN commented
時間があれば、実際にどんなエラーをしやすいかを、口頭でもいいので上げるといいと思います。
例えば
　・インデントがずれていてエラー
　・if文などの「:」の書き忘れ
などですかね。

2018-12-03 03:22 UTC, sanoP1man commented on 3rd/pymee3.md
> +
すいません教えて下さい。。。
FileObjectをリストや辞書で使用するって、どんな形をかんがえてますか？

2018-12-03 05:45 UTC, uranos0601 commented on 3rd/pymee3.md
> +# 例外
単純にファイル読み込みエラーとかですかね。
ただ構文を説明するよりおみくじプログラムに組み込むことで
記憶に残るのではと考えています。

2018-12-03 07:46 UTC, JinKanai commented on 3rd/src/041Summary.py
> +    omikujiList = ["大吉","吉","凶"]
keys()メソッドってやってないんだっけ？ここはkeysでキーを集めたほうがオシャンティですね

2018-12-03 11:33 UTC, sanoP1man commented on 3rd/src/041Summary.py
> +    omikujiList = ["大吉","吉","凶"]
第二回目の対話モードでやってます！

2018-12-03 11:41 UTC, sanoP1man commented on 3rd/pymee3.md
> +
moduleもまだです！
流石に次回で全部は厳しいと思います。
挙げて頂いた業務必須部分は来年度になるかと。。。

2018-12-03 11:44 UTC, sanoP1man commented on 3rd/pymee3.md
> +記載した通り、for文はリストから値を取得する事が前提の作りになっています。
ですね、イテレーターは言わなくていいと思います。

2018-12-03 11:48 UTC, sanoP1man commented on 3rd/pymee3.md
> +
すみません、これは書き方がおかしかったです。
おみくじの中身をひとつのファイルにまとめ、そのファイルを読み込んで出力する形にしたらどうかと伝えたかったです。

2018-12-03 12:49 UTC, JinKanai commented on 3rd/pymee3.md
> +
あー
/3rd/src/041Summary.py ではファイルが分かれてるのでそれをまとめて読み込んだら？という話ですかね
まぁ今回はこれでよいような。

2018-12-03 14:44 UTC, sanoP1man commented on 3rd/pymee3.md
> +
そうです〜。

2018-12-05 18:20 UTC, kotarouikeda commented on 3rd/src/021FileIo.py
> +    print (o);
追記します

2018-12-05 19:16 UTC, kotarouikeda commented on 3rd/src/031Exception.py
> +        output.close()
対応します。

2018-12-05 19:16 UTC, kotarouikeda commented on 3rd/src/041Summary.py
> +
個別でopenのみをexceptで取得するのはやめたほうがいいと考えています。
今回のプログラムではopenの箇所以外エラーは起こらないですが、実際に納品物となると処理途中でエラーが発生して処理が止まるのは確実に避けないといけないので、基本的な考え方としてtry～except句は全ての処理を囲む形にしています。

2018-12-05 19:16 UTC, kotarouikeda commented on 3rd/src/041Summary.py
> +    omikujiList = ["大吉","吉","凶"]
２回目の資料確認しました。
記述をそちらにあわせて修正します。

2018-12-05 19:16 UTC, kotarouikeda commented on 3rd/src/041Summary.py
> +
最終的には１行にまとめた方がいいですが、講義を受ける人にわかりやすいように処理単位で行を分けて記載しています。
なので、このままという事でお願いします。

2018-12-05 19:16 UTC, kotarouikeda commented on 3rd/src/041Summary.py
> +        print (o);
ここも追記します。

＞forの外にprint('\n')を～
これは最後に改行を入れるって事ですかね？

2018-12-05 19:16 UTC, kotarouikeda commented on 3rd/src/041Summary.py
> +    output.close()
確かにそうですね、失礼しました。
ご指摘のとおり修正します。

2018-12-05 19:28 UTC, kotarouikeda commented on 3rd/pymee3.md
> +```
とりあえずコード部分のみ全てこの表記に変更で対応します。

2018-12-05 19:31 UTC, kotarouikeda commented on 3rd/pymee3.md
> ++ 関数
変数を出すなら変数じゃない物は何と呼ぶ？と思って関数という単語を出しました。
とりあえず上記の佐野さんの案で対応します。

2018-12-05 19:34 UTC, kotarouikeda commented on 3rd/pymee3.md
> +#! python3
そう言えばそうでした・・・文字コードだけでなくシェバンも記載しないのを忘れていました。
ソースの方も合わせて全て削除します。

2018-12-05 19:47 UTC, kotarouikeda commented on 3rd/pymee3.md
> +#下記の例文だと0～9の値が入ったリストが作られる。
rangeでのforは単純な処理の繰り返しを作る為に欲しいかと思って入れました。
例えば１分毎にファイルを参照しに行って５回失敗したらエラー出力、といった処理を作るなら単純な回数指定ができればいいかと思って入れましたが、悩みどころですね。
とりあえず資料自体はrange型オブジェクトに記載を修正します。

2018-12-05 19:53 UTC, kotarouikeda commented on 3rd/pymee3.md
> +    print (o);
対応します。

2018-12-05 19:57 UTC, kotarouikeda commented on 3rd/pymee3.md
> +
今回の目的はファイルI/Oの感覚をつかんでもらう所だと思っていますので、ファイルをひとつにまとめてしまうとsplitの処理なんかも入ってくると思うので今回はこの程度にしています。

2018-12-05 19:59 UTC, kotarouikeda commented on 3rd/pymee3.md
> +# 例外
すいません、今回の例外処理はファイル読み込みエラーを採用していますが、どういう形にすればよろしいですかね？
おみくじプログラムに組み込む、という意味では041Summary.pyがそれに当たると考えています。

2018-12-05 20:04 UTC, kotarouikeda commented on 3rd/pymee3.md
> +
＞pythonのforってイテレータオブジェクトから値取り出すだけだっていう説明だけでもいい気がするんだよね・・

私もこれに尽きると思うんですが、実際問題同じ処理をn回繰り返したい時、なんて用件も出てくると思うのでrangeを入れました。
しかし、下手をすると混乱を招きそうな気もしてきました。資料には入れておいて、実際は飛ばして読んで時間が余ったら説明する程度でもよさそうですね。

2018-12-05 20:06 UTC, kotarouikeda commented on 3rd/pymee3.md
> +記載した通り、for文はリストから値を取得する事が前提の作りになっています。
了解です。タプルはもう話でてましたっけ？
取りあえずさらっとリスト以外でも使えますよー、と言ってみます。

2018-12-05 20:51 UTC, kotarouikeda commented on 3rd/pymee3.md
> +【事前準備】
流れとしては例文でその章でやる事をソースコードを見せながら説明(コメントを読みながら補足)、サンプルプログラムは同じ内容の事をおみくじプログラムに当てはめながらやってもらう、というイメージです。
例文のコメント部が説明になってる認識です。

2018-12-05 20:54 UTC, kotarouikeda commented on 3rd/pymee3.md
> +
with openという物があるのをここで知りました・・・
確かに便利そうですね。今回はopen/closeでイメージを掴んで頂き、時間が余った時or次回でやりましょう。

2018-12-05 20:59 UTC, kotarouikeda commented on 3rd/pymee3.md
> +
確かに例外とエラーは別物、という話はどこかで一言いれておいた方がよさそうですね。
ガッツリ説明ではなく、取りあえず一文入れておきます。

2018-12-05 21:30 UTC, kotarouikeda commented on 3rd/pymee3.md
> +#基本的に全部でいい。
基本的に処理の箇所は全部入れておかないとエラーが発生した際に処理が停止して万が一、も避けるのが良いかと思ってこうしましたが・・・今回はエラー発生箇所の特定方法まで入れていませんが、Exceptionの詳細をログに吐かせて(sys.exc_info()等)画面にはエラーだった旨を出力する、といった形になると思うのでこちらの形にしたいです。

2018-12-05 21:42 UTC, kotarouikeda commented on 3rd/pymee3.md
> +
finallyの存在をすっかり忘れていました。
イメージとして一番やりたかった所がここでして、DBのセッションを掴みっぱなしでデッドロックになったり、メモリに展開しっ放しでゴミが溜まっていってしまったりするのを防ぐ為にもここを入れたかったので、修正します。

2018-12-05 21:58 UTC, kotarouikeda commented on 3rd/pymee3.md
> +
＞繰り返し処理第２弾とファイルの書き込み
前回の打ち合わせでこれ言ってましたね。頭だしという事でこの二つだけ記載しておきます。

デバッグに関しては優先度上げたいですね。私はeclipseでやってますが、正直もっと軽くて使いやすいデバッグツールがあればご紹介いただきたい次第で・・・

2018-12-06 00:17 UTC, kotarouikeda commented on 3rd/pymee3.md
> +【今回の講義で利用する知識】
#の利用レベルが統一できてなくてすいません・・・
確かにここは#で良さそうですね。

2018-12-06 00:17 UTC, kotarouikeda commented on 3rd/pymee3.md
> +![](./img/list.png)
図を基準にコードを修正します。

2018-12-06 00:17 UTC, kotarouikeda commented on 3rd/pymee3.md
> +# omikujiという名前の変数に辞書型で一組ずつ「キー：値」の形で格納している。
鍵で統一します。

2018-12-06 00:17 UTC, kotarouikeda commented on 3rd/pymee3.md
> +【例文(for文+Range関数)】
分割対応します。
基準はmarpのpdf出力ですかね？

2018-12-06 00:17 UTC, kotarouikeda commented on 3rd/pymee3.md
> +## サンプルプログラムを作ってみましょう(for文)
出力結果以降で分割します

2018-12-06 00:17 UTC, kotarouikeda commented on 3rd/pymee3.md
> +※今後「IO」と言う単語が出てきますが、「INPUT/OUTPUT」の略称で「入力(読み込み)/出力(表示)」を指しています。
これも統一が必要ですね。INPUT/OUTPUTの略なんでI/Oで統一します。
流石にファイル名には入れられないので文中のみ・・・

2018-12-06 00:17 UTC, kotarouikeda commented on 3rd/pymee3.md
> +for o in output:
今更ながらoutputじゃなくてinputですね・・・ファイル読み込みで取得した物(inputAll)と行に分けた物(inputLine)とかにしてみましょうか。

2018-12-06 00:17 UTC, kotarouikeda commented on 3rd/pymee3.md
> +
open関数の書式についてはもう今はまだおまじないとして覚えてもらおうかと思ってます。
open～closeの流れについてはフローにも記載してくれていますし、口頭説明およびコメントで事足りるかと思っています。

＞FileObjectをリストや辞書で～
後述のファイルを複数openする際にリストや辞書で管理すればわかりやすいのでは、って感じですかね？
できるとは思いますが、プログラムはできるだけシンプルにする方向で書いています。

2018-12-06 00:17 UTC, kotarouikeda commented on 3rd/pymee3.md
> +
あと041Summary.pyを作成する章がないですね・・・大ボケかましてます・・・追加しておきます・・・

2018-12-06 00:17 UTC, kotarouikeda commented on 3rd/pymee3.md
> +# 例外
修正しておきます

2018-12-06 00:43 UTC, sanoP1man commented on 3rd/src/041Summary.py
> +        print (o);
そうです～'\n'で改行を表してます～

2018-12-06 00:52 UTC, sanoP1man commented on 3rd/src/041Summary.py
> +
了解です！

2018-12-06 12:34 UTC, JinKanai commented on 3rd/src/012ForRange.py
> +#range(数字)で0～(記載した数字-1)までの数字が入ったrange型オブジェクト(リストのような物)が作れる。
数字−１とだけ言うと、なんで−１なんだろう。。。と初心者が混乱するかもしれないので、「１０個の数字を用意してくれる。スタートが０からなので、終わりは９です」という説明が当日口頭でできればいいと思います。

2018-12-06 12:34 UTC, JinKanai commented on 3rd/src/041Summary.py
> +
今回は例外処理の紹介なので範囲はなんでもいいと思います。ただ、捕捉する範囲を広げるとそれだけ捕捉する例外の種類も増やさないと駄目（＝実装の工数が増える）なので、そこは参加者に理解させてほしいところです。
テストのカバレッジと同じですね。

2018-12-06 12:36 UTC, JinKanai commented on 3rd/pymee3.md
> +
開いたファイルを辞書とかリストで扱うということかもよ・・・
中山さんのみぞ知る

2018-12-06 12:38 UTC, JinKanai commented on 3rd/pymee3.md
> +#基本的に全部でいい。
例外処理ってこういうことなんだ！というのを理解させれば手法は何でもOKです

2018-12-06 12:41 UTC, JinKanai commented on 3rd/pymee3.md
> +
with openて何も考えずに使うとネストが深くなるのでわしはあんまり好きじゃなかったりするｗ

2018-12-06 12:45 UTC, JinKanai commented on 3rd/pymee3.md
> +記載した通り、for文はリストから値を取得する事が前提の作りになっています。
タプルはやってないし、使いみちの説明も難しいのでpymeeでは触れなくていい気がする（自分で書いてしまいましたが・・・ごめんちゃい）
メソッドから２つ以上の戻り値を戻すときに使うくらい？あれも見た目はパックアンパックしてるんでタプルってのを意識することないしな。。。
タプルはイミュータブルでリストより高速らしいけど、速度を気にするほどのコードも今まで書いたことないな

2018-12-07 01:05 UTC, sanoP1man commented on 3rd/pymee3.md
> +
range使ったforは最後に紹介していた都道府県の問題を作成するプログラムにつかってたので、資料にいれておく形が私もいいと思います！
要件によっても必要になりそうな気がします。

2018-12-07 01:12 UTC, sanoP1man commented on 3rd/pymee3.md
> +【例文(for文+Range関数)】
基準はmarpのpdf出力でもんだいないですよ～

2018-12-08 03:16 UTC, nakayama-akio commented on 3rd/pymee3.md
> +
言葉足らずですみません。
リストや辞書の説明では、箱のイメージ図を使っていたのが分かりやすかったので、ファイル操作の説明にもイメージ図もあればわかりやすいかな。という「図を入れてみてはどうか?」というものでした…ですが、
池田さんの説明通り、おまじないではじめはファイルを開く・閉じるだけの方が入っていきやすいですね。

2018-12-09 13:11 UTC, JinKanai commented on 3rd/pymee3.md
> +# 例外
@uranos0601 これ回答して

2018-12-09 13:37 UTC, JinKanai requested changes
ファイルハンドラのクローズがfinallyになってないのと、１スライドに収まらないページが多いのが気になったです。修正お願いします！

2018-12-09 13:37 UTC, JinKanai commented on 3rd/pymee3.md
> +        output.close()
実行しないからいいですけど、closeの位置はfinallyの中が正かな

2018-12-09 13:37 UTC, JinKanai commented on 3rd/pymee3.md
> +
多分一番簡単なのはこれ
```
import pdb; pdb.set_trace()
```

2018-12-09 13:37 UTC, JinKanai commented on 3rd/src/032FileNotFoundException.py
> +
あれ、前にちゃんと見てなくて申し訳ないけど、closeはfinallyじゃない？

2018-12-09 13:37 UTC, JinKanai commented on 3rd/pymee3.md
> +## サンプルプログラムを作ってみましょう(for文)
治ってない気がするぜ！

2018-12-09 13:37 UTC, JinKanai commented on 3rd/pymee3.md
> +【サンプルプログラム】
ここも１ページに収まってないすね。。。

2018-12-09 13:37 UTC, JinKanai commented on 3rd/pymee3.md
> +![](./img/except_flow.PNG)
フローチャートがはみ出てるでｗ
もしかしてPDFにすると問題なく見れるとか

2018-12-09 13:37 UTC, JinKanai commented on 3rd/pymee3.md
> +【サンプルプログラム】
ここも１スライドに収まってないですね・・

2018-12-09 13:37 UTC, JinKanai commented on 3rd/pymee3.md
> ++ except FileNotFoundError:
読み込みではなくてファイルが見つからないときの例外では？？

2018-12-10 01:14 UTC, HIROSEKAN approved these changes

2018-12-10 23:33 UTC, sanoP1man commented on 3rd/pymee3.md
> +py 02_fileIO.py
01_for.pyに修正必要です～

2018-12-10 23:34 UTC, sanoP1man commented on 3rd/pymee3.md
> +python3 02_fileIO.py
こっちも01_print.pyに修正必要です～

2018-12-10 23:41 UTC, sanoP1man commented on 3rd/pymee3.md
> +    for inputLine in output:
ここのoutputはinputAllのことですか？

2018-12-10 23:44 UTC, sanoP1man commented on 3rd/pymee3.md
> +    inputAll.close()
closeですが、finallyにいれる形に修正お願いします。

2018-12-10 23:47 UTC, sanoP1man commented on 3rd/pymee3.md
> +import random #
末尾の#はいらないと思います～
(細かくてすみません。。。)

2018-12-10 23:49 UTC, sanoP1man requested changes
確認遅くてすみません！

2018-12-11 04:17 UTC, sanoP1man commented on 3rd/pymee3.md
> +import random #
修正しました〜

2018-12-11 04:18 UTC, sanoP1man commented on 3rd/pymee3.md
> +python3 02_fileIO.py
修正しました。

2018-12-11 04:18 UTC, sanoP1man commented on 3rd/pymee3.md
> +py 02_fileIO.py
修正しました。

2018-12-11 04:19 UTC, sanoP1man commented on 3rd/pymee3.md
> +【サンプルプログラム】
分けてはみました。
@kotarouikeda すみません説明の都合上やりにくい場合は、修正お願いします。

2018-12-11 04:19 UTC, sanoP1man commented on 3rd/pymee3.md
> +![](./img/except_flow.PNG)
はみ出てたので倍率を直しました。
文字が小さいので資料をローカルに落としてもらう方が良さそうです。

2018-12-11 04:20 UTC, sanoP1man commented on 3rd/pymee3.md
> +【サンプルプログラム】
直しました〜

2018-12-11 04:20 UTC, sanoP1man commented on 3rd/pymee3.md
> +## サンプルプログラムを作ってみましょう(for文)
修正しました。【サンプルプログラム】の前で一度区切りました。
@kotarouikeda 区切り位置は念の為確認をお願いします。

2018-12-11 05:02 UTC, kotarouikeda commented on 3rd/pymee3.md
> +【例文(ファイルIO)】
ここも出力結果を分割します。

2018-12-11 05:02 UTC, kotarouikeda commented on 3rd/pymee3.md
> +先述のtry～exceptを記載する事で、万が一処理に失敗した場合のフォロー処理を行う事ができます。
では、ここの文章は箇条書きにしてみます。

2018-12-11 05:02 UTC, kotarouikeda commented on 3rd/pymee3.md
> +        output.close()
対応します

2018-12-11 05:02 UTC, kotarouikeda commented on 3rd/pymee3.md
> +```
041Summary.pyにまるごと囲っている理由を記載しておきました。そちらへマージ願います。

2018-12-11 05:02 UTC, kotarouikeda commented on 3rd/pymee3.md
> +サンプルプログラムではexcept句がさらに2か所に分かれています。
同様に対応します。

2018-12-11 05:02 UTC, kotarouikeda commented on 3rd/src/032FileNotFoundException.py
> +
対応します

2018-12-11 05:02 UTC, kotarouikeda commented on 3rd/src/012ForRange.py
> +#range(数字)で0～(記載した数字-1)までの数字が入ったrange型オブジェクト(リストのような物)が作れる。
そうですね。と言うか追記しておきます。忘れそうなので・・・

2018-12-11 05:02 UTC, kotarouikeda commented on 3rd/src/032FileNotFoundException.py
> +
finallyへ以降します。
しかもよく見たらoutputが残ってるので、合わせて修正します。

2018-12-11 05:02 UTC, kotarouikeda commented on 3rd/src/041Summary.py
> +
最終的にはある程度発生が予測されるエラーのみ記載して、残りは全て捕まえてエラーが発生してから解析する形になると考えています。
この形はやめさせた方がいいですかね？

2018-12-11 05:51 UTC, kotarouikeda commented on 3rd/pymee3.md
> +        output.close()
そのままfinallyに入れるとopen時にfileIOexceptionが発生するとopen前なのでcloseする対象が存在せずに別のエラーになってしまう事象が発生しましたので、一文追加してfinallyに以降します。

2018-12-11 05:52 UTC, kotarouikeda commented on 3rd/pymee3.md
> +【サンプルプログラム】
諸々のフォロー、ありがとうございます！

2018-12-11 05:54 UTC, kotarouikeda commented on 3rd/pymee3.md
> +        output.close()
FileNotFoundErrorですね・・・うろ覚えで失礼しました。

2018-12-11 05:56 UTC, kotarouikeda commented on 3rd/pymee3.md
> +    for inputLine in output:
ソースの方にも書きましたが、その通りです・・・

2018-12-11 05:56 UTC, kotarouikeda commented on 3rd/pymee3.md
> +    inputAll.close()
対応します

2018-12-11 06:33 UTC, kotarouikeda commented on 3rd/src/041Summary.py
> +        print (o);
なるほど、対応します。

2018-12-11 08:04 UTC, uranos0601 commented on 3rd/pymee3.md
> +# 例外
すみません、ソース見きれていませんでした。。。
自分のイメージ通り組み込まれていましたのでクローズで！

2018-12-12 00:09 UTC, juke211 approved these changes

2018-12-12 03:32 UTC, sanoP1man commented
レイアウト微修正しました。
こちらでアナウンスします〜

2018-12-13 23:20 UTC, sanoP1man approved these changes

2018-12-26 12:09 UTC, merged