Feature/4th
pymee/studygroup pull request #23
Opened 2019-01-10 03:14 UTC by itoh881

第4回勉強会用のコードを書きました。レビューをお願いします。

2019-01-14 12:35 UTC, JinKanai reviewed
これはダメだ！というのが特にないのでコメントレベルで。他の方の同意があれば修正をお願いします。

2019-01-14 12:35 UTC, JinKanai commented on 4th/omikuji.py
> +#!/usr/bin/python3.6
windowsだとシェバンあると動かないのでなしにする、という事になっていたような。違ってたらごめんなさい

2019-01-14 12:35 UTC, JinKanai commented on 4th/omikuji.py
> +if len(sys.argv) != 2:
コマンドライン引数の説明は時間が余ったらにしますかね。とりあえずはおまじないで今回は済ましますかね。

2019-01-14 12:35 UTC, JinKanai commented on 4th/omikuji.py
> +f = open(sys.argv[1], "r",encoding="utf-8")
せっかくなので前回やった例外処理を入れましょう。説明する時間がありそうならwith文にしてもいいかもです。

2019-01-14 12:35 UTC, JinKanai commented on 4th/omikuji.py
> +wfilename = "kekka_{0}.txt".format(hizuke)
kekka_filename のほうがわかりやすくていいかも。

2019-01-14 12:35 UTC, JinKanai commented on 4th/omikuji.py
> +if os.path.isfile(wfilename):
これって例外でキャッチできないですかね。そのほうが例外を紹介できていいかも。

2019-01-14 12:35 UTC, JinKanai commented on 4th/omikuji.py
> +    sys.exit(1)
エラー終了って前回やってましたっけ。やってないなら、重要な話なんで今回やってもいいかもですね

2019-01-14 17:02 UTC, R-Horio commented on 4th/omikuji.py
> +wfilename = "kekka_{0}.txt".format(hizuke)
```suggestion
wfilename = r"./results/kekka_{0}.txt".format(hizuke)
```
今回のプログラムの場合、役に立たない意見かもしれないですが、
出力先をresultsディレクトリの中とかにすると今後おみくじ結果のファイルが増えても邪魔にならないように出来るかと思います。(フォルダがない場合作成しないとダメですけど...)

2019-01-14 17:02 UTC, R-Horio commented on 4th/omikujifile.txt
> +凶,待人：来ない,失物：増える,恋愛：刺される,転居：燃える
プログラムに全く影響はないですが、"凶"の行は末尾？に改行コードが入っていないので、"大吉・中吉・吉"  と "凶"で結果ファイルの内容（改行のされ方）が微妙に変わってしまっています。(Macでしか試せていません)

2019-01-15 02:44 UTC, R-Horio reviewed
前回の内容から気になった点があったのでそれも少しだけ書いたので確認お願いします。

2019-01-15 02:44 UTC, R-Horio commented on 4th/pymee4.md
> +    print (omikuji);
コードによってセミコロンを付けてあるのと付けていないのがあるので統一したほうが良いと思います。

2019-01-15 02:44 UTC, R-Horio commented on 4th/pymee4.md
> ++ except:
except単体での例外処理は、構文エラーも含めて全てを例外処理してしまい、思わぬバグを生む可能性があるので、注意書き（業務で多様するのは非推奨）を入れたほうが良いかもしれません。

2019-01-15 03:44 UTC, itoh881 commented on 4th/omikuji.py
> +#!/usr/bin/python3.6
```suggestion
```

2019-01-15 03:44 UTC, itoh881 commented on 4th/omikuji.py
> +#!/usr/bin/python3.6
過去の勉強会用コードを確認してもなしになっていましたので削除します。

2019-01-15 04:47 UTC, itoh881 commented on 4th/omikuji.py
> +f = open(sys.argv[1], "r",encoding="utf-8")
with文にして例外処理にします。

2019-01-15 04:48 UTC, itoh881 commented on 4th/omikuji.py
> +wfilename = "kekka_{0}.txt".format(hizuke)
wfilename→kekka_filenameに変更します。

2019-01-15 04:49 UTC, itoh881 commented on 4th/omikuji.py
> +if os.path.isfile(wfilename):
raiseを使用したメリットを提示できる案が浮かばないため一旦例外でキャッチのみ取り入れます。

2019-01-15 04:51 UTC, itoh881 commented on 4th/omikuji.py
> +wfilename = "kekka_{0}.txt".format(hizuke)
resultsにファイル出力するよう変更します。

2019-01-15 04:51 UTC, itoh881 commented on 4th/omikujifile.txt
> +凶,待人：来ない,失物：増える,恋愛：刺される,転居：燃える
改行を削ってしまっていたので付け加えます。

2019-01-17 01:34 UTC, juke211 reviewed
凶の改行部分ぐらいしか気になるとこなかったです。
すでに指摘済みなので、approveしときます。

2019-01-17 01:36 UTC, juke211 approved these changes

2019-01-17 10:44 UTC, kanohiro commented
レビューしました！

2019-01-17 11:02 UTC, kanohiro approved these changes

2019-01-17 23:21 UTC, sanoP1man commented on 4th/omikuji.py
> +if len(sys.argv) != 2:
sysモジュールの説明もすると時間がないと思うので、おまじないでいいと思います。

2019-01-19 10:10 UTC, sanoP1man reviewed
遅くなってすみません！レビュー終わりました。
コメントのみになります〜

2019-01-19 10:10 UTC, sanoP1man commented on 4th/omikuji.py
> +if os.path.isfile(wfilename):
レビューが遅くなってすみません。
すでに考えているかもしれないですが、ファイルをopenする際に'x'で開く形はどうですか？
そうすれば同じファイル名が存在していた場合は'FileExistsError'が発生するので例外のキャッチがしやすいのかなと思います。

2019-01-20 04:00 UTC, JinKanai approved these changes
修正依頼はないので、approveします。

2019-01-20 04:00 UTC, JinKanai commented on 4th/omikuji.py
> +    sys.exit(1)
@kanohiro ↑を資料に反映よろしくお願いします。

2019-01-20 04:00 UTC, JinKanai commented on 4th/omikuji.py
> +
readのところをwithにした場合はこちらもwithにしますかね。ただ、withと普通のやりかたの例をそれぞれ残すためにかたっぽづつでもよいかもです。みなさんの意見を聞きたいです。

2019-01-21 08:06 UTC, itoh881 commented on 4th/omikuji.py
> +if os.path.isfile(wfilename):
xでopenする案を取り入れさせていただきました。

2019-01-21 08:10 UTC, itoh881 commented on 4th/omikuji.py
> +
writeを教えるのは初回なので残すに一票です。

2019-01-22 00:05 UTC, sanoP1man commented on 4th/omikuji.py
> +
writeははじめてということと、withを使わないやり方との比較のためにも、writeはwithにせず残すのに賛成です。
時間があれば、withに書き換えたものを紹介する形にすれば、writeのwithも紹介できていいと思いました。

2019-01-22 01:07 UTC, JinKanai requested changes
ちょいと修正依頼です。

2019-01-22 01:07 UTC, JinKanai commented on 4th/omikuji.py
> +
書いてもらって恐縮ですが、whileの条件としてlineを使っているのにlineの中身を見てbreakしてるのが、ちょっと教材として微妙な感じが・・あと、ファイルの行のリスト化処理をtryにいれているのにそれをキャッチする箇所がないのも微妙です。

根本から変わってしまうんですが、
- readlines()で読み込んで一旦リストに全行を入れる
- tryするのはwithと↑だけ
- while でreadlines()したメソッドから一行づつ取り出して、kekkaList = kekka.split(',')する

とかどうでしょう。
で、whileとforの違いを説明するにあたりなにか仕込みを入れないと駄目なんですが、omikujifile.txtの最後に'EOF'って文字列を入れて、whileでこれが取り出されるまでループするのはどうですかね
これがあれば、イテレータを終わりまで回すforと、何かの条件を満たすまで回すwhileの違いを説明しやすいと思います。

@kanohiro 例外が増えるとそれだけ資料を書くのが大変なので、伊藤さんと調整してください

2019-01-22 01:07 UTC, JinKanai commented on 4th/omikuji.py
> +        sys.stderr.write("エラー:指定されたファイルに読み取り権限がありません。\n")
この例外起こすのめんどくさいっすよｗ

2019-01-22 01:07 UTC, JinKanai commented on 4th/omikuji.py
> +
sys.exit(1)が抜けてる？

@kanohiro ここの例外パターン数も減らすとか増やすとかを調整してください

2019-01-22 01:08 UTC, JinKanai commented
おおチェンジリクエストのアイコンが変わっとる。
さすがに「X」って、付けにくいもんね・・・　これでコメントと修正依頼の区別をはっきりつけやすくなるかな。

2019-01-22 01:47 UTC, JinKanai commented on 4th/omikuji.py
> +
↑だと両方リストやん・・・というツッコミが来る前に、whileで1行づつ取り出しながらEOFが車でループする、というロジックでももちろんOKです。
ただこの場合、try & withでやるとネストが深くなってコードが見にくくなるので、個人的にはopen & closeでやってほしいです。

2019-01-22 03:17 UTC, itoh881 commented on 4th/omikuji.py
> +        sys.stderr.write("エラー:指定されたファイルに読み取り権限がありません。\n")
パーミッション関連のexceptは外そうと思います。

2019-01-22 03:49 UTC, itoh881 commented on 4th/omikuji.py
> +
以下3点満たすように修正しました。
- readlines()で読み込んで一旦リストに全行を入れる
- tryするのはwithと↑だけ
- readlines()で得たリストからwhileで一行づつ取り出して、kekkaList = kekka.split(',')する

readlines()で得たリストからwhileで一行づつ取り出して、kekkaList = kekka.split(',')するために
KekkaListを2次元配列にする必要があると考えたのですが認識はあっていますか？

2019-01-22 05:41 UTC, JinKanai commented on 4th/omikuji.py
> +
readlines()でリスト化した上でwhile使うと2次元になりますね。果たして参加者はこれで理解できるのか・・・

私のイメージはこんな感じ
```
import random

line = ''
kekkalist = []

try:
    f = open('./omikujifile.txt','r')
    while line != 'EOF\n':
        line = f.readline()
        kekkalist.append(line)
    f.close()
except:
    pass

unsei = random.choice(kekkalist)
import random

line = ''
kekkalist = []

try:
    f = open('./omikujifile.txt','r')
    while line != 'EOF\n':
        line = f.readline()
        kekkalist.append(line)
    f.close()
except:
    pass

unsei = random.choice(kekkalist)
```
whileを使わなくてもよい規模のコードに無理やりねじ込むのでこんな変な感じになるけど、まあ説明はできるのかなと。。。
withはwriteのところで使えばいいですかね。ただ今回withをやるかは時間見合いかと思ってます。

2019-01-22 05:45 UTC, JinKanai commented on 4th/omikuji.py
> +
↑のコード、このままだとEOFがおみくじの結果で出てきますねｗ　典型的な境界値判定ミスのバグのいい例なので修正せずにおいときますｗ

2019-01-22 06:50 UTC, itoh881 commented on 4th/omikuji.py
> +
`#引数に読み込むファイルを指定してオープン
try:
    f = open(sys.argv[1], "r",encoding="utf-8")
    line = f.readline()
    while line != "EOF\n":
        KekkaList.append(line)
        line = f.readline()
    f.close

#例外をキャッチした場合の処理内容
except FileNotFoundError:
        sys.stderr.write("エラー:指定されたファイルが見つかりません。\n")
        sys.exit(1)
except PermissionError:
        sys.stderr.write("エラー:指定されたファイルに読み取り権限がありません。\n")
        sys.exit(1)

kekka = random.choice(KekkaList)
unsei = kekka.split(",")`

2019-01-22 07:32 UTC, itoh881 commented on 4th/omikuji.py
> +
無駄に複雑になったとは思っていたので、いただいたコードを参考に書き直しました。
whileのまえにreadlineすることでEOFをリストにappendすることを防いでいます。

2019-01-22 07:39 UTC, JinKanai commented on 4th/omikuji.py
> +
はい、私はこれでOKと思います。ご対応ありがとうございました。
> readlines()使ってイテレータにして、それをforで扱えよとか言い出すような人が今度の勉強会に来ないことを祈るｗ

あとは他のみなさん、whileをもっと上手に見せる方法があればお願いしたいです。

2019-01-22 23:42 UTC, kanohiro commented on 4th/omikuji.py
> +
withを使うとすっきりするのを見せる為にwriteを残すに賛成です。

2019-01-23 15:22 UTC, sanoP1man commented on 4th/omikuji.py
> +
うまく見せる方法思い浮かばなかったです！
「EOF\n」でファイルの終了を検知させることで、forとwhileの違いを明確化できるので問題ないと思います。

2019-01-23 15:23 UTC, sanoP1man commented on 4th/omikuji.py
> +unsei_filename = r"./results/unsei_{0}.txt".format(hizuke)
資料へのコメントではないのですが、
「formatを使用したprint」と「r」については以前の勉強会で何も触れていなかったので説明した方がいいと思います〜！

2019-01-23 15:26 UTC, sanoP1man commented on 4th/omikuji.py
> +
withをどうするかですが、readとwrite両方ともwithを使わずやる方法はどうですか？
時間が余ったらwithの説明をして書き換えてもらう形の方が、資料も作りやすいですし、勉強会の時間調整もしやすいのかなと思いました。

2019-01-23 15:27 UTC, sanoP1man reviewed
あとはwithの扱いをどうするか決めればこちらのコードで問題ないと思います！

2019-01-24 10:15 UTC, itoh881 commented on 4th/omikuji.py
> +
両方とも使わずやる方法でよいかと思います。
というかすみません現状のコードがそうなっています。

2019-01-24 11:53 UTC, JinKanai commented
withは一旦なしにして、資料作成後時間があったら変更、に一票

2019-01-30 00:51 UTC, JinKanai approved these changes
承諾します。

2019-01-30 11:26 UTC, sanoP1man approved these changes
承諾に変更します〜！

2019-01-31 01:03 UTC, merged