Feature/4th documents
pymee/studygroup pull request #24
Opened 2019-02-04 14:49 UTC by kanohiro

第4回pymee資料（pymee4.md）を更新しました。
それに伴い、codeや引数に指定するテキストファイルも追加しております。
レビューよろしくお願いします！
申し訳ありませんが、今回加える予定の章末問題と回答はもう少しお時間下さい。

2019-02-06 13:01 UTC, tatsunakano commented
while文の8行目の意味がちょっとわかりずらく感じます。
引数をwhile.txtから持って来ているのがわからなかったです。
第３回の読み込みを考えるなら
f = open("while.txt", "r",encoding="utf-8”)
でも良いんじゃないでしょうか？
今後の事も考えるなら説明しておくと良いのでは。

\nが改行なことについての記載がないです。
ちょっと調べればわかりますが、いきなり出て来ているので
一言でも記載されていても良いのではないかと考えます。

datetimeモジュールの中のdatetimeクラスだけと
言っても他は何があるんですか？ってなりそうです。

importの所の構文
python3 03_import.py write_file.txt
が記載されていません。

04_summary.pyはすでに使われているので、別のファイル名に
する必要があります。

04_summary.pyの後にomikujifile.txtを入れていないのは
エラーを出させる為にワザと抜いていますか？

私の問題かもしれませんが、04_importを実施したら
完了しない・・・。エラーも出ないので構文が間違っている訳では
なさそうなんですけど。

わからない事ばかりですいません。また細かいことばかりで
申し訳ないです。

2019-02-06 13:26 UTC, itoh881 commented
「サンプルプログラムを作ってみましょう(まとめ)」
でサンプルプログラムを作ってもらう前に、
プログラムのざっくりした流れを伝えておくとわかりやすくなるのではないかと思いました。

例えば今回であればまずは正常系だけで考えてもらうために
正常系
1)おみくじファイルを読み込んでリスト化
2)リスト化したおみくじファイルからランダムで結果を取り出し
3)プログラム実行時の日時取得
4)取り出したおみくじの結果と日付を整形しファイルに書き込み

異常系
1)引数の数をチェック
2)ファイルが読み込みできるかチェック

2019-02-06 22:09 UTC, JinKanai commented
@kanohiro 
前回の資料？との差分が出ていてめちゃくちゃ読みにくいっすねｗ
今回はしょうがないのでよいですが、今後github使うときは最初のレビュー時は新品のファイルをお願いしたいです。

2019-02-06 22:10 UTC, JinKanai commented
@tatsunakano 
上のfiles changedタブをクリックすると今回のレビュー対象のファイル一覧が出てくるんですが、そこでファイルの中に直接コメントを書けます（プルリクの一番強力な機能）
ぜひ次回の指摘から使ってみてください

2019-02-08 01:33 UTC, JinKanai requested changes
全体的に1ページの文章量が多すぎたり少なすぎたりしているので、marpで完成形を確認しながら整形したほうがよいかと思います。
あと、せっかくmarkdownを使っているので、- で箇条書きをしたり、>でコメントや注釈を入れたほうがよいと思います。

@JinKanai 
marpで完成系みながら整形しました。
できるだけ箇条書きにして、長い表現を削りました。

2019-02-08 01:33 UTC, JinKanai commented on 4th/code/01_while.py
> +
末尾の改行は省きましょう〜

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +#読み込むファイルを指定。
これって今回実際には動かさないコードですかね？
どちらにしろ、文字数が多いのでコメント部分は簡略にして```の外に出したほうがよいです
喋っているときに見せるものは少ないほうがよいです

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +#基本的に全部でいい。
以前からありましたが、基本的に全部でよくないのでｗ　この一文は削除しといてください
例外の処理は作業の委任具合で変わるので、この表現はあまり適切ではないです。

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +#例文として存在しないファイルを指定
ここもコメントが多いっすね。もう少し減らしましょう

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +![](./img/except_flow.png)
絵がはみ出てます

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +while文は、繰り返し処理を回し続けるか、ストップするかを条件式で決めることができます。
条件にマッチするまで繰り返す。というシンプルな説明でよいかと。
この文を、話を聞きながら読むのはきついんじゃないかと〜

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +![](./img/while.png)
絵がはみ出てます。

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +## サンプルプログラムを作ってみましょう(while文)
はみ出てます。文字数を削りましょう。

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +最初はnumが0なので、while文の条件を満たし、ブロックの中のコードが実行され、0-9の乱数が発生して変数に格納されます。2回目以降もこの動作を繰り返します。「4以外の数字」の条件を満たす間はループを継続し、num が 4 であれば条件を満たさないので、while文はそこで終了します。
この文章を、説明を聞きながら追うのはしんどいと思います。箇条書きにしてください。
あとページにはタイトルがほしいです

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +引数に指定した "while.txt" から1行ずつ取り出していき、EOFの行に差し当たると条件を満たさないので取り出さずに処理を停止します。<br>
この文章を、説明を聞きながら追うのはしんどいと思います。箇条書きにしてください。
あとページにはタイトルがほしいです

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +![68%](./img/kakikomi.png)
絵ちっちゃいすねｗ
分岐とループがないので、絵は無くても良い気がします。

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +#書き込むファイルを新規作成
ファイルハンドルがオープンされ、ハンドルに書き込まれ・・・という仕組みを説明したほうがよいかと。

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +## サンプルプログラムを作ってみましょう(ファイル書き込み)
１ページが長すぎてはみ出てます。
marpで確認しながらつくるとよいかと。

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +omikuji = open(sys.argv[1], "r",encoding="utf-8")
ここでsys.argvはおまじないって言うんですかね？あとで説明はあるようですが
sysの話をするなら、モジュールのところが適切かなと思います

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +importとは、pythonで書かれたコードを再利用するために使用します。<br>
再利用というのが参加者にはピンとこないような気が・・・
よく使う処理をまとめておいて、好きなときに使えるもの　とか？

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +モジュールとは、pythonのファイル（.py）の事です。<br>
これは誤解を招くような。よく使う機能を他の.pyから利用できるように関数やクラスをまとめたファイル、かな？
あと組み込みモジュールと外部モジュールについて触れましょう

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +ある程度長いプログラムをpythonで書く場合などは、コマンドラインではなく.pyファイルに実行したい内容を保存します。
今コマンドラインから実行してないのであまりピンと来ない説明な気がする（今もファイルに書いているのでは？と思われるような）

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +その保存された.pyファイルは、他のpythonのプログラムからimportで呼び出して使うことが出来ます。<br>
今作っているスタイルのdefとかclassがないコードはimportしても呼び出せないので、そのことに触れたほうがいいかな

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +ただ、モジュールによってはたくさんの.pyファイルが含まれており、全てimportすることでpythonの実行速度を落としてしまうこともあります。
う〜ん、遅くなることよりも、必要なメソッドを使うまでの記載が長くなることとかPYTHONPATHとの絡みが問題な気がするが・・・
ちなみにdatetimeモジュールは単一ファイルで構成されてます。

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +# モジュール（module）とは
ここ以降、改行が多くてページがはみ出てます。改行タグは基本不要です。marpで確認しながら修正してください

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +```python
全部コードブロックに入れると、受講者から見てわかりにくいと思うのでもう少し見やすく修正してください

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +python3 04_summary.py
ココ以降もはみ出てますね・・

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +# その他
ここも改行が多いですね。marpで確認してください

2019-02-08 01:33 UTC, JinKanai commented on 4th/code/04_summary.py
> +f.write(hizuke)
コードレビューのときに指摘してなくて申し訳ないですが、「おみくじを引いた日：」があるといいかも知れないですね

2019-02-08 01:33 UTC, JinKanai commented on 4th/code/while_setsumei.py
> +#while文で条件、および処理を定義「4以外の数字が出るまで変数numで0-9の乱数を表示する」
4が出るまで　では？
4じゃない間　でもOK

while は条件が成立する間ループする　なので、例の場合は否定条件でなくて肯定のほうがわかりやすいかと思うんですが例題書くのが難しいかな・・・

あと、このコードを実行した場合、最後に4が表示されるかされないか、問いかけてもいいかもしれないです。境界判定のいい例題なので。

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +4
あ。答えが出とるｗ　
これもう少し数減らして行数を短めにしてもよいのでは。

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +importはコードの先頭に以下のように記述します。<br>
import入れる場所は使う直前までであればいつでもよいので、そういうふうに記載したほうがよいかと。

2019-02-08 01:33 UTC, JinKanai commented on 4th/pymee4.md
> +そして、もう1つがsys.exit()です。<br>
口頭で説明することを想定しているのであれば、箇条書きに簡潔に書いたほうがよいです

2019-02-08 04:21 UTC, R-Horio requested changes
もしかしたら既出のものもあるかもしれないですが、いくつかレビューさせていただきました。
よろしくお願いします。

2019-02-08 04:21 UTC, R-Horio commented on 4th/pymee4.md
> +	num = random.randint(0,9)
既出かもしれないですが、上のコードではスペース4つをインデントとして使用していますが、このコードではタブになっているので、揃えたほうが良いと思います。
Pythonのコーディング規約？(PEP8)だと半角スペース4つを推奨となっているのでそちらに揃えるのが私は良いと思います。

2019-02-08 04:21 UTC, R-Horio commented on 4th/pymee4.md
> +デスクトップ(どこでもいいです)に作業フォルダを作成し、そこへ以下の名前でテキストファイルを作成して下さい。<br>
数字を振った箇条書きに変えると、事前準備の手順っぽくなるような気がします。
これは好みが出ると思うので、皆さんの意見に合わせたいと思いますが、一つの意見としてレビューさせていただきます。
私のイメージは以下のような感じです。
1. 任意の場所に作業用フォルダを作成
1. 作業用フォルダに`01_while.py`ファイルを作成
1. 作成した`01_while.py`に以下のサンプルプログラムを書いて保存
1. 作業用フォルダに、事前に配布（ダウンロード）したフォルダにある`while.txt`をコピー

2019-02-08 04:21 UTC, R-Horio commented on 4th/pymee4.md
> +引数に指定するテキストファイル (while.txt) はこちらで用意したものを作業フォルダにコピーしておいてください。<br>
今回の使用方法だと、「引数」と表現するより、「コマンドライン引数」と表現するほうが正しいのかなと思います。
もし、コマンドライン引数にするのであれば少しだけ説明が必要だと思います。

2019-02-08 04:21 UTC, R-Horio commented on 4th/pymee4.md
> +ただ、モジュールによってはたくさんの.pyファイルが含まれており、全てimportすることでpythonの実行速度を落としてしまうこともあります。
私が考えていた、モジュール・パッケージ・ライブラリの違いを以下に書いたのですが、もし、認識があっていれば以下のような説明を加えても良いのかなと思いました。
モジュールやパッケージは特に人によって認識の差が出ると思うので、意識合わせも含め知りたいです。

モジュール: 関数(def)やクラス(class)を集めたファイル（.pyファイル）
パッケージ: 複数のモジュールを集めたフォルダ？のようなもの（from パッケージ import モジュール）
ライブラリ: モジュール・パッケージどちらの意味としても呼ばれる曖昧なワード（自分的にはどちらかというとパッケージに近いものとして扱っています）

2019-02-08 04:33 UTC, JinKanai commented on 4th/pymee4.md
> +	num = random.randint(0,9)
ああ、ハードタブはいかんねｗ

2019-02-08 05:45 UTC, JinKanai commented on 4th/pymee4.md
> +ただ、モジュールによってはたくさんの.pyファイルが含まれており、全てimportすることでpythonの実行速度を落としてしまうこともあります。
↑だいたい私もそんな感じです。時間見合いで、ちゃんと説明してもいいかもですね

2019-02-08 07:45 UTC, R-Horio requested changes
追加で気になったところがあったのでコメントしました。
よろしくお願いします。

2019-02-08 07:45 UTC, R-Horio commented on 4th/pymee4.md
> +py 04_summary.py
```suggestion
py 04_summary.py omikujifile.txt
```

2019-02-08 07:45 UTC, R-Horio commented on 4th/pymee4.md
> +python3 04_summary.py
```suggestion
python3 04_summary.py omikujifile.txt
```

2019-02-08 07:45 UTC, R-Horio commented on 4th/pymee4.md
> +import os
```suggestion

```
使われていないimportは消すべきだと思われます。

2019-02-08 07:45 UTC, R-Horio commented on 4th/pymee4.md
> +except:
exceptでFileNotFoundError以外の全ての例外を受け取ってしまうと、SyntaxErrorやAttributeErrorなど全てが`エラー:その他のエラー。`と表示されてしまうため当日に打ち間違えてしまった際にエラーを見ただけでは原因がわからなくなるのでexceptを使うのであればtracebackを使ってエラーを表示くらいささせたほうがいいと思います。
```suggestion
except:
    import traceback
    traceback.print_exc()
```

2019-02-09 00:28 UTC, JinKanai commented on 4th/pymee4.md
> +except:
ここにimportがあると混乱を招きそうな気もしますが、↑の理由を述べた上でおまじないとして記載するのがよいかと思いまうす

2019-02-09 02:58 UTC, R-Horio commented on 4th/pymee4.md
> +except:
「importは一番上に書かなくても使える(使う条件が限られた場合その部分でimport可能)」という実例の一つになるのかなと思いここに書いてみました。
traceback自体は「エラーを教えてくれるおまじない」程度の説明で良いかと思います。

2019-02-09 03:03 UTC, sanoP1man commented on 4th/pymee4.md
> +
randintははじめて扱うものなので、扱う場合は一言説明を入れたほうがいいと思います。

2019-02-09 12:04 UTC, JinKanai commented on 4th/pymee4.md
> +except:
よかろう

2019-02-09 12:04 UTC, JinKanai commented on 4th/pymee4.md
> +
うむそうだな

2019-02-10 10:44 UTC, sanoP1man commented on 4th/pymee4.md
> +![](./img/while.png)
フローチャートの変数名が「s」で、プログラム上だと「num」になっているので合わせた方がいいです。

それと、フローチャートだと繰り返しの判断を一番最後にするように見えてしまうので、最初に書くようにした方が認識に齟齬が出なくていいと思いました。

2019-02-10 10:45 UTC, sanoP1man commented on 4th/pymee4.md
全部コピペでOKにすると、プログラムに書くことになれないと思うので、この一文は記載しなくてもいいかなと思いました。

2019-02-10 10:46 UTC, sanoP1man commented on 4th/pymee4.md
> +#書き込むファイルを新規作成
読み込む際のモード(r,w,xなど)とかの話もしていないので、一度説明した方がいいと思います。

2019-02-10 10:49 UTC, sanoP1man commented on 4th/pymee4.md
> +モジュールとは、pythonのファイル（.py）の事です。<br>
今までrandom.choiseを利用してきたのでこちらを具体例にしたらイメージが湧きやすいかなと思いました。

今まで利用していたrandom.choiceを例にすると。。。
* randomモジュールの中に複数の関数やクラスがある。(ランダムな整数を返すや、リストからランダムに取り出すなど)
* 今までは、その中のchoise関数を使用していた。

利用するには。。。
1.  importでモジュールを読み込む
1.  使用する際にはmodule名.関数名で指定する
* importしないとエラーとなる

2019-02-10 11:01 UTC, sanoP1man commented on 4th/pymee4.md
> +そこで、以下の書式で任意のクラスだけを呼び出すことができます。<br>
dataモジュールに特化しているので任意のクラスだけを呼び出すと記載してもらってると思いますが、
関数もmodule hoge from hoge で読み込めるので「クラス」を「クラスもしくは関数」にした方がいいと思います。

2019-02-10 11:02 UTC, sanoP1man commented on 4th/pymee4.md
>  ---
strftimeやdatetime.nowの説明はサンプルコードを打つ前に説明をしておいた方がいいと思います。
サンプルコードだと情報量が多くて、参加する人がうまく飲み込めないと思うので。

2019-02-10 11:02 UTC, sanoP1man commented on 4th/pymee4.md
> +unsei_filename = r"./results/unsei_{0}.txt".format(hizuke)
rもなんでrをつける必要があるかフォロー入れた方がいいと思います。

2019-02-10 11:13 UTC, sanoP1man commented on 4th/pymee4.md
> +
ここでreadline()を利用しているので、資料最後のreadlineはこの章で説明してもいいと思いました。

2019-02-10 11:17 UTC, sanoP1man commented on 4th/pymee4.md
まとめコードですが、tatsunakanoさんと同意見でどんな流れか説明した方がいいと思いました。
その際に、利用する下記関数等は簡単に説明した方がわかりやすいかなと思います。

* append()
* splits()
* sys.exit()

2019-02-10 11:18 UTC, sanoP1man requested changes
レビュー遅くなってすみません。レビュー終わりました。
先にどんなコードを書くか説明してからサンプルコードを参加者に書いてもらった方が理解が深まると思います。

2019-02-13 00:31 UTC, kanohiro commented
> while文の8行目の意味がちょっとわかりずらく感じます。
> 引数をwhile.txtから持って来ているのがわからなかったです。
> 第３回の読み込みを考えるなら
> f = open("while.txt", "r",encoding="utf-8”)
> でも良いんじゃないでしょうか？
> 今後の事も考えるなら説明しておくと良いのでは。

第3回の読み込み方法に変更しました。
それに伴い、02_file_write.py、03_import.pyも同様に変更しました。

> \nが改行なことについての記載がないです。
> ちょっと調べればわかりますが、いきなり出て来ているので
> 一言でも記載されていても良いのではないかと考えます。

コメント追記しました。

> datetimeモジュールの中のdatetimeクラスだけと
> 言っても他は何があるんですか？ってなりそうです。

datetimeパッケージの中のdatetimeモジュールに変更し、
他のモジュールを追記しました。

> importの所の構文
> python3 03_import.py write_file.txt
> が記載されていません。

記載しました。

> 04_summary.pyはすでに使われているので、別のファイル名に
> する必要があります。

"04.summary_4th.py"に変更しました。

> 04_summary.pyの後にomikujifile.txtを入れていないのは
> エラーを出させる為にワザと抜いていますか？

入れ忘れました。追記してあります。

> 私の問題かもしれませんが、04_importを実施したら
> 完了しない・・・。エラーも出ないので構文が間違っている訳では
> なさそうなんですけど。

04_summaryの実行すかね? 
コピーしたomikujifile.txtのEOFの後に改行入ってないとか?

2019-02-13 00:44 UTC, kanohiro commented on 4th/code/01_while.py
> +
省きましたー

2019-02-13 00:49 UTC, kanohiro commented on 4th/pymee4.md
> +#読み込むファイルを指定。
復習コードなので動かさない想定でしたが、これまでどうだったんすかね？
コメント削って外出ししました。

2019-02-13 00:49 UTC, kanohiro commented on 4th/pymee4.md
> +#基本的に全部でいい。
削りましたー

2019-02-13 00:51 UTC, kanohiro commented on 4th/pymee4.md
> +#例文として存在しないファイルを指定
削って外出ししました。

2019-02-13 01:24 UTC, kanohiro commented on 4th/pymee4.md
> +![](./img/except_flow.png)
縮小してMarpで1ページに収まることを確認しました。

2019-02-13 01:25 UTC, kanohiro commented on 4th/code/04_summary.py
> +f.write(hizuke)
format()でまとめコードに追加しました。

2019-02-13 01:30 UTC, kanohiro commented on 4th/code/while_setsumei.py
> +#while文で条件、および処理を定義「4以外の数字が出るまで変数numで0-9の乱数を表示する」
> 4が出るまで　では？
> 4じゃない間　でもOK
修正しました。

> while は条件が成立する間ループする　なので、例の場合は否定条件でなくて肯定のほうがわ> かりやすいかと思うんですが例題書くのが難しいかな・・・

すんません、思いつかず、少し調べても出てこず。。
肯定条件に関しては、サンプルプログラムの方で紹介できるので、とりあえずいいのかなと。

2019-02-13 01:30 UTC, kanohiro commented on 4th/pymee4.md
> +4
短くしときましたー

2019-02-13 01:31 UTC, kanohiro commented on 4th/pymee4.md
> +そして、もう1つがsys.exit()です。<br>
項目分けて箇条書きにしました。

2019-02-13 01:31 UTC, kanohiro commented on 4th/pymee4.md
> +	num = random.randint(0,9)
修正しました。

2019-02-13 01:33 UTC, kanohiro commented on 4th/pymee4.md
> +デスクトップ(どこでもいいです)に作業フォルダを作成し、そこへ以下の名前でテキストファイルを作成して下さい。<br>
ナイスアイデア！
まるまる作業手順になると思うので、作業手順としました。

2019-02-13 01:37 UTC, kanohiro commented on 4th/pymee4.md
> +引数に指定するテキストファイル (while.txt) はこちらで用意したものを作業フォルダにコピーしておいてください。<br>
コマンドライン引数に変更し、sys.argvの項目にコマンドライン引数の説明を追加しました。

2019-02-13 14:05 UTC, kanohiro commented on 4th/pymee4.md
> +except:
traceback追加しました。

2019-02-13 14:06 UTC, kanohiro commented on 4th/pymee4.md
> +
コード中にコメントで追記しました。

2019-02-13 14:07 UTC, kanohiro commented on 4th/pymee4.md
削除しました。

2019-02-13 14:11 UTC, kanohiro commented on 4th/pymee4.md
> +そこで、以下の書式で任意のクラスだけを呼び出すことができます。<br>
堀尾さんの案を取って、パッケージから任意のモジュールのみ呼び出すと表現を変えましたが、いかがでしょうか？

2019-02-13 14:12 UTC, kanohiro commented on 4th/pymee4.md
>  ---
サンプルコードの前に説明を追加しました。

2019-02-13 14:12 UTC, kanohiro commented on 4th/pymee4.md
> +unsei_filename = r"./results/unsei_{0}.txt".format(hizuke)
raw文字列の説明を追加しました。

2019-02-13 14:12 UTC, kanohiro commented on 4th/pymee4.md
> +
移動しました。

2019-02-13 14:13 UTC, kanohiro commented on 4th/pymee4.md
流れ、および関数の説明を纏めコードの前に移動しました。

2019-02-13 14:13 UTC, kanohiro commented on 4th/pymee4.md
> +import os
削除しました。

2019-02-13 14:21 UTC, kanohiro commented on 4th/pymee4.md
> +importはコードの先頭に以下のように記述します。<br>
表現を変えました。

2019-02-17 05:39 UTC, R-Horio approved these changes

2019-02-17 23:09 UTC, sanoP1man commented on 4th/pymee4.md
> +#読み込むファイルを指定。
以前場合、復習用コードは動かさずに説明のみでした！

2019-02-18 01:33 UTC, juke211 approved these changes
帰省中のため、確認が遅れました。

2019-02-18 14:33 UTC, JinKanai requested changes
勉強会の資料は、講師が書かないとダメだなというのが改めてよくわかるいい機会でしたｗ
とりあえず資料は修正してもらって、講師は時間見合いで、いるとこいらないとこを厳選して取り扱って当日2時間以内に収めましょう

2019-02-18 14:33 UTC, JinKanai commented on 4th/pymee4.md
> +```
フローチャートと変数が違うって指摘があったけど治ってない？

2019-02-18 14:33 UTC, JinKanai commented on 4th/pymee4.md
> +リストの中にリストが追加されました。
なんでリストにリスト足すんですかね。見てる人混乱しないですかね

2019-02-18 14:33 UTC, JinKanai commented on 4th/pymee4.md
> +
お題で偶数を表示させるなら、演算例で偶数を見つける演算子を使ったほうがわかりやすいのでは？

2019-02-18 14:33 UTC, JinKanai commented on 4th/pymee4.md
> +
よくわかんないんだけど、これは講師が実演してるってこと？

2019-02-18 14:33 UTC, JinKanai commented on 4th/pymee4.md
> +
ここでtimedeltaの例題だして、参加者は回答できるだけの知識を与えられてるんだっけ？

2019-02-18 14:33 UTC, JinKanai commented on 4th/pymee4.md
> +
これなんですか？

2019-02-18 14:33 UTC, JinKanai commented on 4th/pymee4.md
> ++ 今後のよりよい活動のため、アンケートにご協力ください！
アンケートは一番最後でお願いします

2019-02-18 21:50 UTC, JinKanai commented
@kanohiro あと私の伝え方が悪かったのですが、プルリクを発行したあとにファイルを入れ替えると、指摘時との差分が消えてしまうのでそれはやめたほうがよいです。
プルリク発行前にファイルが新規になるようにしましょう、という意味でした。

2019-02-19 04:24 UTC, sanoP1man commented on 4th/pymee4.md
> +リストの中にリストが追加されました。
サンプルプログラムの予習の場合、リストをappendしなくても大丈夫かなと思います〜
サンプルプログラムもリストにリストを追加するだけなので。

2019-02-19 04:38 UTC, sanoP1man commented on 4th/pymee4.md
> + 1. while文で条件を満たす限り1行ずつリストに追加
```suggestion
 1. while文で条件（読み込んだ行がEOLでない）を満たす限り読み込んだ行をリストに追加し、次の行を読み込む
```
条件を明示的に書いた方がわかりやすいと思います。
また、whileの条件を満たす間、リスト追加と次の行読み込みが繰り返されることが少し伝わりにくいと思ったのでこんな文章はどうでしょうか。

2019-02-19 13:46 UTC, kanohiro commented on 4th/pymee4.md
> +#読み込むファイルを指定。
あざす！

2019-02-19 14:40 UTC, sanoP1man commented on 4th/pymee4.md
> +日付や時刻に対して色々な操作をすることが出来るモジュールを集めたdatetimeパッケージには、以下のようなモジュールが含まれています。
一つ目のdatatimeってパッケージでしたっけ？
datatime.datatime.nowの場合、最初のdatatimeはモジュールで二つ目のdatatimeはクラス、最後のnowクラス関数の認識です。
最初のレビューで指摘漏れてたらすみません。
timedelta, date, timeもモジュールでなくて、クラスだと思います。

2019-02-19 14:46 UTC, sanoP1man commented on 4th/pymee4.md
> +
年ー月ー日ではなく、yyyy/mm/ddのフォーマットにしてもらうとかどうですか？

2019-02-19 14:56 UTC, sanoP1man commented on 4th/pymee4.md
> +hizuke = datetime.now().strftime("%Y-%m-%d")
%Y、%m、%dってなんだ！？となる気がします。

このコードの下でいいので、ディレクティブの説明をした方がいいと思います〜！

ディレクティブ  説明
%Y     4桁の西暦(1989、2019)
%m     0うめした月（04、12）
%d      0うめした日付(01、31)

2019-02-19 15:08 UTC, sanoP1man commented on 4th/pymee4.md
> ++
次回は来年度の活動になりますので、正直まだきまってません！
なので、ここは削除しちゃって大丈夫です！

2019-02-19 15:10 UTC, sanoP1man commented on 4th/pymee4.md
> +
不明点はメーリングリストで気軽に聞いて下さい！
という一文をアンケートのページに追加してもらえればこのスライドは消しちゃって大丈夫です〜

2019-02-19 15:11 UTC, sanoP1man requested changes
遅くなって本当申し訳ないです。
モジュール部分で確認したいので、すみませんが確認お願いします。

2019-02-19 17:37 UTC, kanohiro commented on 4th/pymee4.md
> +```
治しました。

2019-02-19 17:38 UTC, kanohiro commented on 4th/pymee4.md
> +リストの中にリストが追加されました。
「リストに要素をappendする」に変更しました

2019-02-19 17:39 UTC, kanohiro commented on 4th/pymee4.md
> +
パッと出てこないので、解答に説明追記しました。

2019-02-19 17:40 UTC, kanohiro commented on 4th/pymee4.md
> +
出力結果を追記しました。実演用のappend-1.py、append-2.pyをcodeフォルダに追加しました。

2019-02-19 17:41 UTC, kanohiro commented on 4th/pymee4.md
> +
日付フォーマットを変更する問題に変えました。

2019-02-19 17:43 UTC, kanohiro commented on 4th/pymee4.md
> +
前回資料の遺物です。削除しました。

2019-02-19 17:43 UTC, kanohiro commented on 4th/pymee4.md
> ++ 今後のよりよい活動のため、アンケートにご協力ください！
最後にしました。

2019-02-19 17:45 UTC, kanohiro commented on 4th/pymee4.md
> + 1. while文で条件を満たす限り1行ずつリストに追加
ありがとうございます！反映しました。

2019-02-19 17:46 UTC, kanohiro commented on 4th/pymee4.md
> +日付や時刻に対して色々な操作をすることが出来るモジュールを集めたdatetimeパッケージには、以下のようなモジュールが含まれています。
まるっと変更してみました。クラスの説明が難しく、何かいい表現ないすかね？

2019-02-19 17:47 UTC, kanohiro commented on 4th/pymee4.md
> +hizuke = datetime.now().strftime("%Y-%m-%d")
追加しました。ディレクティブ自体の説明も入れてみたので、ご確認お願いします。

2019-02-19 17:47 UTC, kanohiro commented on 4th/pymee4.md
> ++
削除しました。

2019-02-19 17:47 UTC, kanohiro commented on 4th/pymee4.md
> +
アンケートページにマージしました。

2019-02-19 23:25 UTC, sanoP1man commented on 4th/pymee4.md
> +
ありがとうございます！

2019-02-19 23:42 UTC, sanoP1man commented on 4th/pymee4.md
> +日付や時刻に対して色々な操作をすることが出来るモジュールを集めたdatetimeパッケージには、以下のようなモジュールが含まれています。
クラスの説明難しいですね。

今回の勉強会では確実に説明できないので、インスタンス化の部分はふれずに、「複数の関数などをまとめたもの、クラス自身に値を渡してもなんらかの処理が可能」でいいのかなと思います。

2019-02-19 23:46 UTC, sanoP1man commented on 4th/pymee4.md
> +
ヒントが答えになってるので、ちょっと修正した方がいいかなと思います～

時間、分、秒のディレクティブを、ディレクティブの一覧に追加して、
問題のヒントはディレクティブの一覧を確認してみよう！にするのはどうですか？

2019-02-19 23:48 UTC, sanoP1man commented on 4th/pymee4.md
> +hizuke = datetime.now().strftime("%Y-%m-%d")
対応ありがとうございます！
フォーマットを変える問題でもコメントいれましたが、時間、分、秒をいれてもいいかなと思います。

2019-02-20 00:08 UTC, JinKanai commented on 4th/pymee4.md
> +日付や時刻に対して色々な操作をすることが出来るモジュールを集めたdatetimeパッケージには、以下のようなモジュールが含まれています。
Datetimeは単体ファイルで提供されているのでモジュールという認識
クラスについては、関数をまとめた物くらいの説明で今回は良いのでは
まぁ本当はメソッドなんだけど、、

2019-02-20 00:12 UTC, JinKanai commented on 4th/pymee4.md
> +日付や時刻に対して色々な操作をすることが出来るモジュールを集めたdatetimeパッケージには、以下のようなモジュールが含まれています。
- import datetime
だけにして、
- datetime.datetime.now() 
でいいんじゃないかと。
Fromの説明は予備知識が必要で結構難しい気がする
これじゃながいでしょ? 実は短くする方法もあるのでまた今度!でいいんじゃないでしょうか

2019-02-20 01:59 UTC, kanohiro commented on 4th/pymee4.md
> +日付や時刻に対して色々な操作をすることが出来るモジュールを集めたdatetimeパッケージには、以下のようなモジュールが含まれています。
import datetimeだけの説明にしました。それに伴い、03_import.py と 04_summary_4th.pyも修正しました。

2019-02-20 01:59 UTC, kanohiro commented on 4th/pymee4.md
> +hizuke = datetime.now().strftime("%Y-%m-%d")
入れてみましたー

2019-02-20 03:00 UTC, sanoP1man commented on 4th/pymee4.md
> +日付や時刻に対して色々な操作をすることが出来るモジュールを集めたdatetimeパッケージには、以下のようなモジュールが含まれています。
@JinKanai たしかに、importのみの方が混乱しなくて良さそうですね。

2019-02-20 04:56 UTC, JinKanai requested changes
import datetime
モジュール（＝ファイル）をインポート

datetime.datetime.now()
モジュール（＝ファイル）のdatetimeクラスのnow()メソッド呼び出し

ですかね。
import datetimeにしたコードはdatetime.datetime.**を使わないとだめなので該当箇所をすべて修正する必要があります。
動作確認を事前にしとかないと当日参加者は相当混乱すると思われるｗ

2019-02-20 04:56 UTC, JinKanai commented on 4th/code/datetime_setsumei.py
>  date1 = datetime.now()
ここも直さないとだめでは・・

2019-02-20 04:56 UTC, JinKanai commented on 4th/pymee4.md
> +import datetime
datetime.datetime.now()にしないと動かないかと・・・

2019-02-20 23:21 UTC, sanoP1man commented on 4th/pymee4.md
> +hizuke = datetime.now().strftime("%Y-%m-%d")
修正ありがとうございます！
ここも、datetime.datetime.now()に修正が必要そうです。

2019-02-20 23:22 UTC, sanoP1man commented on 4th/pymee4.md
> ++ datetime.nowで取得した日付と時刻を "Y-M-D" というフォーマットに変更できました。
datetime.datetime.now() に修正お願いします〜

2019-02-20 23:28 UTC, sanoP1man commented on 4th/pymee4.md
> +hizuke = datetime.now().strftime("%Y-%m-%d")
こちらもdatetime.datetime.now() に修正だ必要そうです〜

2019-02-20 23:30 UTC, sanoP1man commented on 4th/pymee4.md
> +hizuke = datetime.now().strftime("%Y-%m-%d")
datetime.datetime.now()に修正お願いします！

2019-02-20 23:36 UTC, sanoP1man commented on 4th/pymee4.md
> +hizuke = datetime.now().strftime("%Y-%m-%d")
ここもdatetime.datetime.now()に修正必要です〜

2019-02-20 23:38 UTC, sanoP1man commented on 4th/pymee4.md
> ++ 今後のよりよい活動のため、アンケートにご協力ください！
アンケートまだできてないので、配布資料からは削除しません？
当日は別資料でプロジェクターに写すだけにすればいいかなと思いました。

2019-02-20 23:40 UTC, sanoP1man requested changes
datetime.datetime.now() に直した方がいいところコメント入れました〜
それと、アンケートまだできてないので、配布資料からは削除したらどうですか？

@sanoP1man 
QRコードとアンケートリンクだけ削りました。

2019-02-21 02:51 UTC, kanohiro commented on 4th/code/datetime_setsumei.py
>  date1 = datetime.now()
直しました。動作確認済みです。

2019-02-21 02:52 UTC, kanohiro commented on 4th/pymee4.md
> +import datetime
コードとともに修正しました。

2019-02-21 02:52 UTC, kanohiro commented on 4th/pymee4.md
> ++ datetime.nowで取得した日付と時刻を "Y-M-D" というフォーマットに変更できました。
修正しました。

2019-02-21 02:52 UTC, kanohiro commented on 4th/pymee4.md
> +hizuke = datetime.now().strftime("%Y-%m-%d")
コードともに修正しました。

2019-02-21 02:53 UTC, kanohiro commented on 4th/pymee4.md
> +hizuke = datetime.now().strftime("%Y-%m-%d")
修正しました。

2019-02-21 09:25 UTC, JinKanai commented
アンケート記載しましたが職場のMACのせいか変な改行が入ってます。あんま気にしないでください

2019-02-21 14:14 UTC, sanoP1man commented on 4th/pymee4.md
> +print("import_kekka.txtに書き込みました!")
元ファイルをコピーしてきたので、結果の文章を変える必要があります。
```suggestion
###########   write_kekka.txtをimport_kekka.txtに変更  ##########

print("import_kekka.txtに書き込みました!")

####################################################

```

2019-02-21 14:26 UTC, sanoP1man commented on 4th/pymee4.md
> +===============================
細かくて申し訳ないです。。。
f.write("\n")があるので実際には改行が入るので改行追加してもらえないでしょうか。
```
===============================
【大吉】
待人：辛抱強く待つべし
失物：足元にあり
恋愛：深入りするな
転居：無理せず待て

===============================
```

2019-02-21 14:27 UTC, sanoP1man commented on 4th/pymee4.md
> +2019-02-03
f.write("\n")があるので、ここにも改行が入ります〜

2019-02-21 14:28 UTC, sanoP1man commented on 4th/pymee4.md
> +転居：無理せず待て
ここにもf.write("\n")があるので、日付の上に改行が入ります〜

2019-02-22 04:53 UTC, sanoP1man approved these changes

2019-02-22 04:53 UTC, sanoP1man commented
フローチャートの修正ありがとうございます。確認しました。

2019-02-22 07:22 UTC, JinKanai approved these changes

2019-02-25 01:23 UTC, JinKanai approved these changes
操作間違えましたｗ

2019-03-30 06:58 UTC, JinKanai commented
このプルリクはいつ閉じれるんだ・・・ｗ

2019-03-31 13:55 UTC, sanoP1man commented
資料とコードの一部を修正しました。
資料の修正箇所は下記の通りです。
一旦こちらでmasterにマージします！

* 「ファイル読み込み」のprint (o, end='');の「;」を削除
* 「例外」のinputAll.close()をinput.close()に修正
* 「サンプルプログラムを作ってみよう(ファイル書き込み)」の【サンプルプログラム】で「omikuji」をcloseしていないので追記
* 「サンプルプログラムを作ってみよう(モジュール)」の【サンプルプログラム】(3/3)にomikuji.close()を追加

2019-03-31 13:56 UTC, closed without merging