Tatsunakano patch 2
pymee/studygroup pull request #29
Opened 2019-09-25 15:00 UTC by tatsunakano

2019-10-04 17:59 UTC, sanoP1man requested changes
遅くなってすみません！ひとまず基本編のコードのみレビューしました。
ディスカッションの際、pymee事務局でのコード説明が20分しかないので、基本編のコードのみしか説明できないかもしれません。

2019-10-04 17:59 UTC, sanoP1man commented on 20191011sample/command_pymee.py
> +#!/user/bin/env python3
シェバンの説明していないので、無しでもいいですか？

2019-10-04 17:59 UTC, sanoP1man commented on 20191011sample/command_pymee.py
> +    print("Usage: {} <csvfile>".format(sys.argv[0]), file=sys.stderr)
`file=sys.stderr`があるところ、ないところがあるので統一した方がいいと思います。
また、`file=sys.stderr`は去年の勉強会でやっていないので、追加する場合はなぜつけるかの説明が必要です〜

2019-10-04 17:59 UTC, sanoP1man commented on 20191011sample/command_pymee.py
> +
`sys.argv[1]`ですが頻繁に登場するので変数に格納した方が見やすいし編集しやすいと思いました。

2019-10-04 17:59 UTC, sanoP1man commented on 20191011sample/command_pymee.py
> +
`["", "", "password", "command"]`のようにパスワードしか値が入っていない場合も以前の情報を使用してアクセスすることになるので、以下のように修正が必要と思います。

```python
    for row in csv_reader:
        if not(row[0] =="" and row[1]=="" and row[2] == "") :
            hostname = row[0]
            ip = row[1]
            password = row[2]
        command = row[3]
```

2019-10-04 17:59 UTC, sanoP1man commented on 20191011sample/command_pymee.py
> +
以下の要件があるため、`stdout`の先頭が`[ユーザ名@`で始まらない場合はプロンプトを追加するようにしないといけないです。
* プロンプトが取れない場合、rootユーザは`[ユーザ名@ホスト名]# `とし、それ以外は`[ユーザ名@ホスト名]$ `とする

AWSのプロンプトはrootユーザの場合`[root@ip-172-16-18-11 ~] #`、その他ユーザの場合`[username@ip-172-16-18-11 ~] $` なのでちょっと面倒です・・・

2019-10-04 17:59 UTC, sanoP1man commented on 20191011sample/command_pymee.py
> +        raise FileExistsError()
openのモードを`x`にすれば同じ名前のファイルがあった際にエラーが発砲されるので、あえてエラーをraiseしなくてもいいと思います。

2019-10-04 17:59 UTC, sanoP1man commented on 20191011sample/command_pymee.py
> +elif os.path.getsize(sys.argv[1]) <= 10:
空ファイルの検知なので条件式は`サイズが0の場合`でいいかなと思いました。

2019-10-04 17:59 UTC, sanoP1man commented on 20191011sample/command_pymee.py
> +
他のエラーでSSH接続ができない場合もあると思うので、その他エラーの検知もつけた方がいいと思います。
```python
except:
     print("ERROR: その他エラーが発生しました。", file=sys.stderr)
     sys.exit(1)
```

2019-10-04 17:59 UTC, sanoP1man commented on 20191011sample/command_pymee.py
> +
今回はカレントディレクトリに結果ファイルを保存するためresultフォルダの作成は不要かと〜！

2019-10-05 07:13 UTC, R-Horio commented on 20191011sample/command_pymee.py
> +
@sanoP1man 
要件定義の資料だけで把握しきれていませんでした。すみません。
実際には以下のようなパターンが考えられるという認識で大丈夫ですか？
またrootユーザでSSH接続するときにはユーザ名が指定されていますか？
```
IPアドレス,ログインユーザ名,ログインパスワード,コマンド
,,ログインパスワード,コマンド
,,,コマンド
```

2019-10-05 07:13 UTC, R-Horio commented on 20191011sample/command_pymee.py
> +#!/user/bin/env python3
@sanoP1man 削除します。

2019-10-05 07:19 UTC, R-Horio commented on 20191011sample/command_pymee.py
> +    print("Usage: {} <csvfile>".format(sys.argv[0]), file=sys.stderr)
@sanoP1man `file=sys.stderr`は有りで統一します。
説明はやっぱりあったほうがいいですか？
前年度と勉強会の形態も違うので、`file=sys.stderr`はそんなに難しくないので、気になった人は各自で調べるというのも面白いと思います。

2019-10-05 07:20 UTC, R-Horio commented on 20191011sample/command_pymee.py
> +
@sanoP1man 
`csv_file_path`という変数を用意してそこに格納するようにします。

2019-10-05 07:32 UTC, R-Horio commented on 20191011sample/command_pymee.py
> +elif os.path.getsize(sys.argv[1]) <= 10:
@sanoP1man 
`elif os.path.getsize(csv_file_path) == 0`に変更します

2019-10-05 07:32 UTC, R-Horio commented on 20191011sample/command_pymee.py
> +
@sanoP1man 
同じフォルダに保存するように編集します。

2019-10-05 08:01 UTC, R-Horio commented on 20191011sample/command_pymee.py
> +
@sanoP1man 
exceptだとSyntax Errorも例外処理するのでもう少し細かい設定にしたほうがいいと思います。
せめてbacktraceか`except as e`でエラー内容を見せないと危険だと思います。

2019-10-05 08:06 UTC, R-Horio commented on 20191011sample/command_pymee.py
> +
@sanoP1man 
コメントのミスがありました。リスト内包表記は使ってないです。（最初は使っていました）
プロンプトが取れないというと、認証エラーが出たらrootで接続を試みて接続成功したら`[ユーザ名@ホスト名] $`を結果のファイルに出力するということですか？
最初の方の話し合いにほとんど参加出来ていないので分かっていない部分が多いのですが、今回のプログラムはrootにSSH接続してなにかコマンドを実行する必要があるということですか？

2019-10-05 08:11 UTC, R-Horio commented on 20191011sample/command_pymee.py
> +
@sanoP1man あと、`[ユーザ名@ホスト名]`は結果出力のどの部分に入れ込めばいいですか？

2019-10-05 08:12 UTC, R-Horio commented on 20191011sample/command_pymee.py
> +        raise FileExistsError()
@sanoP1man xに変えました。

2019-10-05 08:24 UTC, R-Horio commented on 20191011sample/command_pymee.py
> +
@sanoP1man ParamikoのドキュメントのExceptionのページです。
[公式どきゅめんと](http://docs.paramiko.org/en/2.6/api/ssh_exception.html)
ドキュメントを見た感じだと、`AuthenticationException`でSSH接続系の例外処理はだいたいできそうな感じがします。

2019-10-05 15:19 UTC, R-Horio commented on 20191011sample/command_pymee.py
> +
@sanoP1man 
SSH接続の際に引数で渡したtimeoutの時間を過ぎたら、以下の例外に飛ぶようにしました。
```python
except socket.timeout:
    print("ERROR: タイムアウトしました。", file=sys.stderr)
    sys.exit(1)
```

2019-10-05 15:57 UTC, R-Horio commented on 20191011sample/command_pymee.py
> +
@sanoP1man 
プロンプトは手動での生成になりますが以下の感じのコードで作ってみました。
コードに反映済みなので試してみてください。
```python
stdin, stdout, stderr = ssh.exec_command("echo $HOSTNAME")
server_hostname = stdout.readline().strip("\n")
prompt = "[{user}@{hostname}]".format(user=username, hostname=server_hostname)
prompt += "# " if username == "root" else "$ "
```

2019-10-05 23:38 UTC, sanoP1man commented on 20191011sample/command_pymee.py
> +
お願いします～！

2019-10-05 23:41 UTC, sanoP1man commented on 20191011sample/command_pymee.py
> +
お願いします～！

2019-10-06 16:59 UTC, sanoP1man commented on 20191011sample/command_pymee.py
> +    print("Usage: {} <csvfile>".format(sys.argv[0]), file=sys.stderr)
`file=sys.stderr`有りに統一了解です！
説明ですが、資料には記載せずに、口頭で`file=sys.stderr`は標準エラーに出力させるための引数です、詳細が気になる人は調べてみてください！ぐらいにするのはどうですか？

2019-10-06 17:06 UTC, sanoP1man commented on 20191011sample/command_pymee.py
> +
@R-Horio コメントがわかりにくくてすみません！

> 実際には以下のようなパターンが考えられるという認識で大丈夫ですか？

今回準備したcsvファイルは以下の形なので私がパスワードしか値が入っていない場合はないです。
ただ、このファイルを実際使う場合、パスワードしか入っていない場合も考慮しておいたほうがいいかと思ってコメントしました。

* 参加者に案内したcsvファイル
```
IPアドレスA,ユーザA,パスワード,hostname
IPアドレスA,root,パスワード,ifconfig
IPアドレスA,ユーザA,パスワード,top -b -n 1
IPアドレスB,root,パスワード,hostname
,,,ifconfig
,,,top -b -n 1
```

> またrootユーザでSSH接続するときにはユーザ名が指定されていますか？

rootユーザでSSH接続する場合、rootユーザでログインしています。
すみません、見当違いのこと言ってたらコメントください。。。

2019-10-06 17:19 UTC, sanoP1man commented on 20191011sample/command_pymee.py
> +
@R-Horio 
修正コードありがとうございます！ちょっと別途確認します。

> プロンプトが取れないというと、認証エラーが出たらrootで接続を試みて接続成功したら[ユーザ名@ホスト名] $を結果のファイルに出力するということですか？

コマンド実行結果でプロンプト部分が出力されていなかったという事象を想定しており。
その事象が発生した場合は、こちらが準備したプロンプトを実行結果に書き込むことを考えていました。
(ただ、そんな事象ほとんど考えられない気がしてきました。。。)


> 今回のプログラムはrootにSSH接続してなにかコマンドを実行する必要があるということですか？

今回のプログラムでは、ifconfigがrootでないと実行できなかったので、rootでSSH接続してコマンド実行してます。

> [ユーザ名@ホスト名]は結果出力のどの部分に入れ込めばいいですか？

出力結果の先頭に入れ込む形です〜

2019-10-06 18:21 UTC, sanoP1man commented on 20191011sample/command_pymee.py
> +
@R-Horio 
確認ありがとうございます！
電源を入れいていないサーバに対してparamikoでSSH接続したところ以下のエラーが出力されました。
なので、タイムアウト時に発砲されるエラーは`socket.timeout`ではなく`paramiko.ssh_exception.NoValidConnectionsError`のようです。

```
Traceback (most recent call last):
  File "/home/ec2-user/environment/test_para.py", line 9, in <module>
    client.connect('172.31.16.127', username='test', password='test')
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 368, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 172.31.16.127
```
[公式どきゅめんと](https://docs.python.org/2.7/library/socket.html#socket.error)の`17.2.2. Example`を見ると、`socket.error`は`socket`モジュールを利用している際に発砲されるエラーのようにみえます。

2019-10-06 18:23 UTC, sanoP1man commented
遅くなってすみません、コメント返しましたので確認をお願いします。

2019-10-06 20:46 UTC, R-Horio commented on 20191011sample/command_pymee.py
> +
paramikoのソース読んでみたら、NoValidConnectionError自体はsocket.errerを継承しているみたいなので、NoValidConnectionErrorを使うようにします。

2019-10-09 12:50 UTC, R-Horio commented on 20191011sample/command_pymee.py
> +    print("Usage: {} <csvfile>".format(sys.argv[0]), file=sys.stderr)
@sanoP1man 口頭での紹介で大丈夫だと思います！

2019-10-09 12:53 UTC, R-Horio commented on 20191011sample/command_pymee.py
> +
@sanoP1man CSVファイルの詳細ありがとうございます。
現段階でのコードは以下のようにしています。
```python
 if not (row[0] == "" and row[1] == "" or row[0] == "" and row[1] == "" and row[2] == ""):
```
※PWとコマンドしか入っていない場合とコマンドしか入っていない場合です。

2019-10-09 13:08 UTC, R-Horio commented on 20191011sample/command_pymee.py
> +
@sanoP1man 実際に試して見たのですが、NoValidConnectionErrorでタイムアウトを例外でキャッチすることは出来なかったので、`socket.timeout`と`NoValidConnectionError`の両方を例外処理として使うことにします。

2019-10-09 13:12 UTC, R-Horio reviewed
レビューして頂いた内容をコードに反映させてPUSHしました。
接続時の例外処理はsocket.timeoutとNoValidConnectionErrorの両方を使うことにしました。

2019-10-10 13:48 UTC, sanoP1man commented on 20191011sample/command_pymee.py
> +#!/user/bin/env python3
お願いします！

2019-10-10 13:49 UTC, sanoP1man commented on 20191011sample/command_pymee.py
> +
@R-Horio 了解です！確認ありがとうございます。

2019-10-21 16:04 UTC, sanoP1man requested changes
遅くなってすみません、説明資料もコメント入れたので確認をお願いします

2019-10-21 16:04 UTC, sanoP1man commented on 20191011sample/README.md
> +
シェバン部分の削除をおねがいします〜。
これは任せますが、コードには書かずに、別スライドでシェバンの説明を追加してもいいと思います。

2019-10-21 16:04 UTC, sanoP1man commented on 20191011sample/README.md
> +
元のプログラムを直していると思うので、説明文は修正をお願いしますー！

2019-10-21 16:04 UTC, sanoP1man commented on 20191011sample/README.md
> +
私もこれすごい便利だと思いました！

2019-10-21 16:04 UTC, sanoP1man commented on 20191011sample/command_pymee.py
> +
@R-Horio 
すみません、ちょっと教えてください。
今回記載しているエラー以外が発生した場合、処理が途中で止まることってあります？

その場合は、except:でその他エラーを全部取得し、ひとまず処理が途中で止まらないようにする形になるのでしょうか。

2019-10-21 16:04 UTC, sanoP1man commented on 20191011sample/README.md
> +elif os.path.getsize(sys.argv[1]) <= 10:
以下のコメントの追加をお願いします
`# コマンドライン引数で指定したファイルのサイズを調べ・・・`

2019-10-21 16:04 UTC, sanoP1man commented on 20191011sample/README.md
> +1. コマンド実行。3つの戻り地があるので3つの変数に代入してます。
`値`が`地`になっているので修正お願いします。

2019-10-21 16:04 UTC, sanoP1man commented on 20191011sample/README.md
> +1. リスト内包表記でstdout変数の中の文字列をリストにする
これはリスト内包表記ではなく、出力結果の整形を行なっているのかなと。
出力結果の１行分を取り出し、行頭と行末の改行を削除、行末に改行を追加するという動きを出力結果の最後になるまで繰り返しているので、stdout変数の中をリストにはしてないかなと思います。

2019-10-21 16:04 UTC, sanoP1man commented on 20191011sample/README.md
> +
２番目のfor文というのは`for row in csv_reader:`の部分だと思うのですが、パッと読んだところ`for i in stdout:`のfor文と勘違いしそうなので、`項番2のfor文(for row in csv_reader:)で項番3〜7を・・・`の方がわかりやすいかなと思いました。

2019-10-21 16:04 UTC, sanoP1man commented on 20191011sample/README.md
> +
ここら辺はコードの修正と合わせて変更をお願いいます。

2019-10-21 16:25 UTC, sanoP1man commented on 20191011sample/README.md
> +![flowchart](./img/pymee2019_sample.jpg)
フローチャートの作成もありがとうございます！
元コードを修正していると思うので、フローチャートも修正をお願いします〜。

1つ相談なのですが、「サーバに接続」や「ファイル書き込み時」に記載しているエラー処理をフローチャートに載せます？
エラーをキャッチした際も異常終了するけど、異常終了の部分に矢印が伸びてなかったのでちょっと気になりました。

2019-11-01 12:35 UTC, R-Horio commented
README.mdを一旦更新したので、レビューお願いします。
できるだけ早くフローチャートとMarp用のMarkdownを作るのでお待ちください。

2019-11-21 04:39 UTC, sanoP1man approved these changes
確認がかなり遅くなってすみません。。。
また、修正ありがとうございます！修正内容確認しました。

2020-02-06 10:24 UTC, sanoP1man commented
こちらクローズし忘れていたので、クローズします。

2020-02-06 10:24 UTC, closed without merging