第1回勉強会用コード　最終レビュー
pymee/studygroup pull request #4
Opened 2018-06-27 00:43 UTC by JinKanai

（余計な差分があったので作り直し）

勉強会で使用するコードの最終レビューをお願いします。

2018-06-27 01:24 UTC, JinKanai reviewed
レビューしました。おおむね問題ないと思うので、私の意見は無視でもOKです～

2018-06-27 01:24 UTC, JinKanai commented on 1st/code/04-2_list.py
> +
-１との差って、choiceメソッド使ってるだけですかね。であれば、１はなしでいいと思いますよ。
「randam.choiceは、渡されたリストからランダムで要素を選んでくれるすごいやつです、なんでか知らんけど。なんでか知らんけど仕事をしてくれる、これがオブジェクト指向のカプセル化です！」とか適当に話せばいいと思います。

もしくは、6でリストをchoiceに食わしているので、逆に-２をなくすか。

2018-06-27 01:24 UTC, JinKanai commented on 1st/code/05_dict.py
> +
辞書化したのに辞書のキーを使ってvalueを取り出してないのが気になりますが・・・まぁ、、いいかな・・・
unsei_key = randam.choice(list(omikuji.keys()))
print(omikuji[unsei_key])
のほうがおシャンティかな。。と思ったり。

2018-06-27 02:28 UTC, juke211 commented on 1st/code/05_dict.py
> +
議事録見たら、dictをkeyで取り出すと書いてありましたね。。
しかも、06でkeyからvalueを取り出してるので、あれってなりますね。
修正します！

2018-06-27 03:45 UTC, JinKanai reviewed
追記しました

2018-06-27 03:45 UTC, JinKanai commented on 1st/code/06_nest.py
> +		{'all':'中吉! まぁまぁよし。 ','work':'仕事運:定時で帰れます！'},
今気づいたけど、fortuneになってるのでomikujiに修正かな・・

2018-06-27 03:45 UTC, JinKanai commented on 1st/code/07_if_in.py
> +luck = random.choice(fortune)
luckも、unseiのほうがいいかな・・・

2018-06-27 03:45 UTC, JinKanai commented on 1st/code/04-1_list.py
> +
for文を組み込むなら、ここで一覧表示させてもいいかもしれないです。一覧表示したのと、ランダムに選んだのを続けてだしてもいいと思いますよ

2018-06-27 04:14 UTC, juke211 commented on 1st/code/05_dict.py
> +
修正済み

2018-06-27 04:14 UTC, juke211 commented on 1st/code/06_nest.py
> +		{'all':'中吉! まぁまぁよし。 ','work':'仕事運:定時で帰れます！'},
修正済み

2018-06-27 04:14 UTC, juke211 commented on 1st/code/07_if_in.py
> +luck = random.choice(fortune)
修正済み

2018-06-27 04:15 UTC, juke211 commented on 1st/code/04-1_list.py
> +
修正済み

2018-06-27 04:44 UTC, JinKanai reviewed
確認しました。問題ないです。

2018-06-27 04:44 UTC, JinKanai commented on 1st/code/04-1_list.py
> +  print(x)
確認しやした～

2018-06-27 04:44 UTC, JinKanai commented on 1st/code/05_dict.py
> +
対応ありがとうございます！

2018-06-27 04:44 UTC, JinKanai commented on 1st/code/07_if_in.py
> +if '吉' in unsei['all']:
ばっちりです！

2018-06-27 04:49 UTC, juke211 commented on 1st/code/04-2_list.py
> +
議事録では、段階を踏ませるって感じでしたけど
ここは、話で繋げればコードは飛ばしてもわかる気がしますね。

2018-06-28 12:12 UTC, sanoP1man reviewed
レビューします～

2018-06-28 16:26 UTC, sanoP1man approved these changes
レビューしました！
細かいんですが、途中で大凶が増えたり、小吉が減ったりしているのでおみくじの数は統一したほうがいいと思います！
そのほかの部分は問題ないです。
ただ、forについてはコメントした通り相談させてください。

2018-06-28 16:26 UTC, sanoP1man commented on 1st/code/04-1_list.py
> +
初めてプログラミング触る人にもわかりやすいよう、ファイルの項番があがるごとに、どんどんおみくじアプリに機能が追加されてったほうがわかりやすいかなと思ってます。なので、突然forがでてきてびっくりしないですかね？
forは2回目の最初にやってもいいかなと思いました。

2018-06-28 20:41 UTC, JinKanai commented
@sanoP1man 初approveありがとうごぜーます。

しかし！修正点とか検討することが残っているうちはまだapproveしてはいけません！
そういうときは遠慮なくchange requestにして、自分の指摘が納得行く形で終息したら初めてapproveできます。
なので一回直しときましょうか。

2018-06-28 20:42 UTC, JinKanai commented
forについて。確かに @sanoP1man のおっしゃる通り。せっかく追加してもらって申し訳ないけど、修正しようかな。
@juke211 私やってもいいですか？

ストーリーは大事ですね。

2018-06-29 02:34 UTC, JinKanai commented on 1st/code/04-1_list.py
> +
テスト

2018-06-29 02:39 UTC, JinKanai commented
@juke211 修正ありがとうございました。しかもプッシュしてくれるなんて。

今度の勉強会で詳しくやりますが、今回の場合、小野さんはpymeeのメンバーなのでfolk→プルリクする必要はなく、ここをクローンしてこのブランチに直接コミット＆プッシュでOKです。
＃fork→プルリクは、気に入ったプロジェクトに参加したいときに、「こんなん作ったんですけどどうですか・・・？」とお伺いを立てるときに使うそうです。

もし意図的な実施でしたらすみません。今後はこちらに直接プッシュでOKです！
ブランチ運用については、勉強会で詳しく解説しますのでどうぞお楽しみに。

2018-07-01 01:43 UTC, sanoP1man requested changes
レビュー結果修正しました。

2018-07-01 01:48 UTC, sanoP1man approved these changes
おみくじの中身の修正と、forの削除確認しました。

2018-07-01 09:47 UTC, juke211 approved these changes

2018-07-06 10:54 UTC, nakayama-akio reviewed
遅れてすみません…
確認しました。気になるところは特にありません。
※たぶん関数/変数修正の過程でコメント部とコードの差異が残ってるのだと思います(#fortune->omikuji、 randint->randrange)が、動作影響ないので大丈夫です。

2018-07-08 00:52 UTC, juke211 commented
@nakayama-akio  修正忘れていました。
明日修正します。

2018-07-25 05:53 UTC, JinKanai commented
（コミットメッセージをクリックしたら直前のコミットとの差分だけが見れるんだけど、そこでコメントするとここに自動で出てくるんだ・・・知らなかった・・・）
（プルリク出てない場合はどうなるんだろう・・・）

2018-08-21 00:28 UTC, closed without merging