発表用の資料を作成しました、レビューお願いします。
pymee/studygroup pull request #7
Opened 2018-07-16 11:21 UTC by sanoP1man

発表用の資料をmarkdownで作成しました。pdf版はtocaroにアップします。
とりあえず、レビュアーを全員にしていますが、tocaroにコメントでも問題ないです。
githubの方がレビューしやすい人はレビューをお願いします。

2018-07-17 02:51 UTC, juke211 commented on 1st/doc/pymee1.md
> ++ 修正後
修正前と修正後が一緒の気がします。

2018-07-17 02:55 UTC, juke211 commented on 1st/doc/pymee1.md
> +unsei_key = random.choice(list(omikuji.keys()))
修正前と後で内容が一緒になってる気がします。

2018-07-17 07:36 UTC, JinKanai requested changes
とりあえず一旦ここまで。
typoがあるようなのでCRにします。

2018-07-17 07:36 UTC, JinKanai commented on 1st/doc/pymee1.md
> +
以下は番号リストにしたほうが見やすいかも知れないですね
1. ほげ
1. もげ

2018-07-17 07:36 UTC, JinKanai commented on 1st/doc/pymee1.md
> +	+ 指示内容を機械がわかるような形で翻訳する
インタプリタは、プログラムを逐次実行してくれるものです。
上の記載だと、コンパイラも当てはまるかな。

```
プログラムを実行するには実行環境が必要。
環境には大きく2種類ある。
- インタプリタ
- コンパイラ
```
みたいな？

2018-07-17 07:36 UTC, JinKanai commented on 1st/doc/pymee1.md
> ++ 指示内容の記載に使用する言葉
これは上に書いてあるので記載なしでいいかな～

2018-07-17 07:36 UTC, JinKanai commented on 1st/doc/pymee1.md
> ++ プログラミング言語の一種
つづけて、
- pythonには2と３があって、2は廃止予定なこと
- pymeeでは3しか使わないこと
を書いておくとよいかと。

2018-07-17 07:36 UTC, JinKanai commented on 1st/doc/pymee1.md
> +	+ プログラムを実行
これは記載ミス？

2018-07-17 07:36 UTC, JinKanai commented on 1st/doc/pymee1.md
> +1. 勉強用フォルダを作成
フォルダ名称はこちらから指定したほうが悩む時間なくさくっと先に進めるかな？

2018-07-17 07:36 UTC, JinKanai commented on 1st/doc/pymee1.md
> +$ python test.py
python3 にしておいたほうが無難です。

2018-07-17 07:36 UTC, JinKanai commented on 1st/doc/pymee1.md
> ++ Pythonのインストール
pythonは事前に入れてきてもらう前提ですかね。

2018-07-17 07:36 UTC, JinKanai commented on 1st/doc/pymee1.md
> +python ファイル名
windowsだと、py.exeになるかな。

2018-07-17 07:36 UTC, JinKanai commented on 1st/doc/pymee1.md
> ++ Unix/系のプラットフォームで使用、windowsは記載する必要がない
#8 で議論中ですが、シェバンは今回なくてもいいかもしれないですね。chmodはwindowsでは使えないし、私が言い出して申し訳ないですが、私は今回触れなくていいかな、と思います。

2018-07-17 07:36 UTC, JinKanai commented on 1st/doc/pymee1.md
> +# # coding: utf-8
#9 にある通り、これも今回なしでいいかな・・・でもwindowsでshiftJISでセーブしちゃった人は、coding: shift_jis付けないと日本語扱えないですね・・・

2018-07-17 07:36 UTC, JinKanai commented on 1st/doc/pymee1.md
> +Pythonでは自動で判別のため、データ型の宣言は不要
宣言があることのメリデメを記載したいですね
- メリット→変数型をコンパイラが判定しなくていいので早い
- デメリット→型宣言がめんどくさい！

あと、宣言が必要な言語も名前だけ紹介しときましょうか
c ,  javaなどなど

2018-07-17 07:36 UTC, JinKanai commented on 1st/doc/pymee1.md
> +# 型ではデータをしまう箱
typo?

2018-07-17 07:36 UTC, JinKanai commented on 1st/doc/pymee1.md
> +print(type("あなたの運勢は、大吉すべてよし"))
ここはインタプリタでやったほうがよくないかな？？

2018-07-17 10:18 UTC, sanoP1man commented on 1st/doc/pymee1.md
> ++ Pythonのインストール
pythonは事前に入れてきてもらう予定です。
なので、展開メールにインストールをやってもらうよう記載し、インストール方法がわからないようだったら連絡もらうようにしようかなと思います。
問い合わせ先はpymee用のメーリングリスト(申請中)にする予定です。

2018-07-17 10:27 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +
項目番号で修正します。

2018-07-17 10:38 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +	+ 指示内容を機械がわかるような形で翻訳する
こんな感じで説明しようと思います。
> プログラムを実行するには実行環境が必要。
> 環境には大きく2種類ある。
> - インタプリタ
> 　翻訳しながら逐次実行する。手間が少ない(コンパイルの時間が不要のため)。
> - コンパイラ
> 　いったん翻訳して、翻訳結果を別途実行する。比較的実行処理が速い。

2018-07-17 10:52 UTC, sanoP1man commented on 1st/doc/pymee1.md
> ++ プログラミング言語の一種
python3のみであることを強調する
インストール先を案内メールにつける
2.8系はでない、python3を使おう！
pythonについて、蛇じゃないよ。
※issueにする、#でissueがでてくる、@でメンバーがでてくる
※pullrequで議論がでてきたらissueを案内する
※最初にissueたって、プルリクが発生する

2018-07-17 10:55 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +	+ プログラムを実行
意図が伝わりにくいので、修正する
実行して、でてくる部分を伝えたかった。

2018-07-17 10:57 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +1. 勉強用フォルダを作成
フォルダ名は「pymee1」を作成にする

2018-07-17 10:58 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +$ python test.py
pythonだけだと、2や3が動く場合があるので。
python3にする

2018-07-17 11:18 UTC, JinKanai commented on 1st/doc/pymee1.md
> +# # coding: utf-8
windowsでもutf-8で保存を強制！

2018-07-17 11:23 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +print(type("あなたの運勢は、大吉すべてよし"))
インタプリタで確認する
インタプリタの会話モードへ移動するコマンドをつける

2018-07-17 12:45 UTC, sanoP1man commented on 1st/doc/pymee1.md
> ++ 指示内容の記載に使用する言葉
@JinKanai このコメントの意図を思い出しましたらコメント下さい～

2018-07-22 23:05 UTC, sanoP1man commented on 1st/doc/pymee1.md
> ++ Unix/系のプラットフォームで使用、windowsは記載する必要がない
#8 であるように、シェバンは今回触れない形にします。

2018-07-22 23:05 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +Pythonでは自動で判別のため、データ型の宣言は不要
こちら、追記します！

2018-07-22 23:06 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +# 型ではデータをしまう箱
タイポです。直します。

2018-07-24 07:19 UTC, JinKanai requested changes
とりあえず業務の息抜きにレビューしました。
続きはまた明日・・・

書き忘れてましたが、段落のタブが全部ハードタブ（いわゆる\t）になってます。
最近のコードは4文字ソフトタブを使うことが多いので、修正をお願いしたく・・・
\t → "    "（スペース４つ）の一発置換でできます。

最近ハードタブ使うのってmakefileくらいしか見たことないけど、普通なのかな・・・？

2018-07-24 07:19 UTC, JinKanai commented on 1st/doc/pymee1.md
> +	+ 処理を書いた言語のことをプログラミング言語→Python
ちょっと記載がわかりにくいかな～とおもいました
> 処理を書いた言語のことをプログラミング言語→Python

↓
処理を書く言語のことをプログラミング言語という。
いろんな種類があって、その１つがpython

こんな感じ？？

> まだ書きかけだったらごめんなさい

2018-07-24 07:19 UTC, JinKanai commented on 1st/doc/pymee1.md
> +	+ 型をしまう箱の種類
型をしまう～　でなくて、
値をしまう～　のほうがわかりやすいかな

2018-07-24 07:19 UTC, JinKanai commented on 1st/doc/pymee1.md
> ++ Bool(True, False)
厳密にはboolean

2018-07-24 07:19 UTC, JinKanai commented on 1st/doc/pymee1.md
> +	+ Flase, classなど
> Flase

falseか・・・？

2018-07-24 07:19 UTC, JinKanai commented on 1st/doc/pymee1.md
> ++ 先頭が数字、もしくはアンダースコアは使えない
文面の指摘ではないんですが、ここから先、markdownとしてパースされなくなってるので、この行の前に改行を入れたほうがいいかもです。

2018-07-24 07:19 UTC, JinKanai commented on 1st/doc/pymee1.md
> +print(type("あなたの運勢は、大吉すべてよし"))
ココの先で対話モードの話が出てくるんですね
ここで対話モード使うか、先までひっぱるかは、おかませします！

2018-07-24 07:19 UTC, JinKanai commented on 1st/doc/pymee1.md
> +# 完成コード
このページmarpでpdf化するとはみ出るかも・・・

2018-07-24 07:19 UTC, JinKanai commented on 1st/doc/pymee1.md
> +	+ 値が格納する箱のラベル
値が　→　値を

2018-07-24 07:19 UTC, JinKanai commented on 1st/doc/pymee1.md
> +なので、任意のおみくじが出力されるようにプログラムを改良しよう！
任意の使い方が違うような・・・
ランダムで～　でいいような気がする。

2018-07-24 07:19 UTC, JinKanai commented on 1st/doc/pymee1.md
> ++ 0-4の数字から任意の数字を選ぶ
すげー細かい話ですが、数字を選ぶのは人間でなくrandom関数なので、
0~4からランダムで選ぶ
などの書き方のほうがしっくりきます

2018-07-24 07:19 UTC, JinKanai commented on 1st/doc/pymee1.md
> +```
randomの詳細は時間見合いで省くことも考えましょうか。
個人的には、今回は「おまじないです」程度の解説でいい気もします。

2018-07-24 07:19 UTC, JinKanai commented on 1st/doc/pymee1.md
> +>>> if unsei == 0:
対話モードでifのようなインデント入るのやるのは結構大変かも！です。
printの前にタブを押すことを説明しないと大変なことに・・・！？

2018-07-25 07:38 UTC, JinKanai requested changes
レビュー終わりました！指摘は一杯ありますが、修正、相談などよろしくお願いします！

2018-07-25 07:38 UTC, JinKanai commented on 1st/doc/pymee1.md
> ++ 今まで、箱を1つづつ用意し、その中に値を代入
今までは〜代入していた
のほうが自然かな

2018-07-25 07:38 UTC, JinKanai commented on 1st/doc/pymee1.md
> ++ 大きな箱の中身は0から始まる番号が振られており、こちらを元に値を取り出すことが可能
中身には

2018-07-25 07:38 UTC, JinKanai commented on 1st/doc/pymee1.md
> +> リスト名[offset]
口頭でカバーするならOKですが、いきなりオフセットって言葉が出てくると？？？ってなるかもです。

2018-07-25 07:38 UTC, JinKanai commented on 1st/doc/pymee1.md
> +	['大吉', '中吉', '小吉', '吉', '吉']
吉が1個復活した！？ｗ
ココの前に、さっき削除した吉を追加するか、中吉を消すか、ですかね。

2018-07-25 07:38 UTC, JinKanai commented on 1st/doc/pymee1.md
> +> リスト名.append(値)
appendで吉を復活させてもいいかも。

2018-07-25 07:38 UTC, JinKanai commented on 1st/doc/pymee1.md
> ++ 定義した順番に表示されない
表示されないけど、リストと違って要素の並び順でなく鍵で取り出すので問題ない、ということに触れましょう。

2018-07-25 07:38 UTC, JinKanai commented on 1st/doc/pymee1.md
> +
ここのポイントは、
- インデックスをランダム生成→リストから取り出し
と2ステップだったのが
- リストからランダムで取り出し
の１ステップになったこと、だと思うので、もっとそれを強調してもいいかもです。
コード的には1行しか変わってないので、みんなあまりピンとこないかも。

2018-07-25 07:38 UTC, JinKanai commented on 1st/doc/pymee1.md
> +	+ 辞書、文字列
あれ、辞書って値の書き換えできるよ？
```
>>> dict = {'a':1,'b':2}
>>> dict
{'a': 1, 'b': 2}
>>> dict['a']=3
>>> dict
{'a': 3, 'b': 2}
````

文字列の書き換えができないってのは・・・何のことを言ってる？

2018-07-25 07:38 UTC, JinKanai commented on 1st/doc/pymee1.md
> +unsei_key = random.choice(list(omikuji.keys()))
先に、omikuji.keys()でkeyだけ取り出せるのを実演したほうがいいですね。

2018-07-25 07:38 UTC, JinKanai commented on 1st/doc/pymee1.md
> +>>> omikuji.keys()
あ、ここでやってるんですね、失礼・・・

2018-07-25 07:38 UTC, JinKanai commented on 1st/doc/pymee1.md
> +unsei_key = random.choice(list(omikuji.keys()))
ほんまや

2018-07-25 07:38 UTC, JinKanai commented on 1st/doc/pymee1.md
> +print(name + 'さんの運勢は、' + unsei['all']+ '\n' + unsei['work'])
\nで改行ですってのを説明したほうが、いいですね（前にあったらごめんちゃい）

2018-07-25 07:38 UTC, JinKanai commented on 1st/doc/pymee1.md
> +unsei = random.choice(omikuji)
今更コードへの突っ込みで申し訳ないですが、ここでprint(unsei)すると取り出せたものが見れてより理解が深まるかと思ったり。

2018-07-25 07:38 UTC, JinKanai commented on 1st/doc/pymee1.md
> ++ 「含まれていた場合」には「in」を使用する
文字列にある文字が含まれているかを確認するにはinを使う、てほうがわかりやすいかな

2018-07-25 07:38 UTC, JinKanai commented on 1st/doc/pymee1.md
> +if '吉' in unsei['all']:
if文は、条件が真（true）であれば下の行を実行し、偽（false）であればelseもしくはifを終了、という説明が必要ですね

2018-07-25 07:38 UTC, JinKanai commented on 1st/doc/pymee1.md
> +	print('こういう日もあります。元気出してくだい！！')
ください！
あれ、これコードの修正が必要かな？

2018-07-25 07:38 UTC, JinKanai commented on 1st/doc/pymee1.md
> ++ 「in」は「〜を含んでいる」という比較演算子
if文の説明も・・・

2018-07-25 10:48 UTC, JinKanai commented on 1st/doc/pymee1.md
> +	print('こういう日もあります。元気出してくだい！！')
コードの方はちゃんと「ください！」になってましたね

2018-07-25 23:24 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +python ファイル名
windowsだと、py ファイル名 になると記載します！

2018-07-25 23:28 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +print(type("あなたの運勢は、大吉すべてよし"))
ボリュームみあいになるかもですね。
ちょっも、検討します。

2018-07-25 23:31 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +	+ 処理を書いた言語のことをプログラミング言語→Python
言語は複数あって、その一つがpythonのほうがわかりやすそうですね。
修正します！

2018-07-25 23:34 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +	+ Flase, classなど
うちまちがえです。。。

2018-07-26 00:28 UTC, nakayama-akio commented on 1st/doc/pymee1.md
> +	+ 今年度はPython勉強会を企画
Python meeting？

2018-07-26 00:28 UTC, nakayama-akio commented on 1st/doc/pymee1.md
> +「大吉 すべてよし 」を出力されることを確認する
を出力されることを確認する
⬇︎
が出力されることを確認する

がいいかなと思います。

2018-07-26 00:28 UTC, nakayama-akio commented on 1st/doc/pymee1.md
> +変数名「name」を入力、もしくはpirnt(name)を実行して入力した名前が表示されることを確認
もしくはpirnt(name)
↓
もしくはprint(name)

2018-07-26 00:28 UTC, nakayama-akio commented on 1st/doc/pymee1.md
> +| 要素になっている| in | x in 1| xに1が含まれている|
x in 1 だと、xは1に含まれているか？
(検索する側  in  検索される側)
の方が検索したい文字/値(in左側)と検索される側(in右側)を意識しやすいかなと思います。

x in y   で、xはyに含まれているか?  とか…

2018-07-26 09:08 UTC, kotarouikeda commented on 1st/doc/pymee1.md
> +	+ 「python3.6」と入力
#10 でお話しした通り、Windowsだと「py」だけで最新バージョンのpythonでインタプリタの対話モードが起動してくれましたので記載願います。

2018-07-26 09:08 UTC, kotarouikeda commented on 1st/doc/pymee1.md
> +# # coding: utf-8
まず73行目のファイル作成の時点で注意を促した方がいいですかね。
SJISで保存しちゃってたら作り直させてもいいですが。

2018-07-26 14:06 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +	+ 今年度はPython勉強会を企画
meetingでした！修正します！

2018-07-26 14:19 UTC, sanoP1man commented on 1st/doc/pymee1.md
> ++ 指示内容の記載に使用する言葉
「指示内容の記載に使用する言葉」は削除して、プログラミング言語の部分を修正します。

2018-07-26 14:54 UTC, sanoP1man commented on 1st/doc/pymee1.md
> ++ Bool(True, False)
修正します！

2018-07-26 15:07 UTC, sanoP1man commented on 1st/doc/pymee1.md
> ++ 先頭が数字、もしくはアンダースコアは使えない
アンダースコアがmarkdownでは文字をイタリック書体に修飾するという意味でした、なのでパースされなくなっていたようです。
なのでアンバーバーの前にバックスラッシュを入れて、エスケープします。

2018-07-26 15:10 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +	+ 「python3.6」と入力
記載します！

2018-07-26 15:10 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +「大吉 すべてよし 」を出力されることを確認する
修正しました！

2018-07-26 15:12 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +# 完成コード
ギリギリ大丈夫そうです。。。

2018-07-26 15:12 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +	+ 値が格納する箱のラベル
修正しました！

2018-07-26 15:13 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +なので、任意のおみくじが出力されるようにプログラムを改良しよう！
修正しました！

2018-07-26 15:14 UTC, sanoP1man commented on 1st/doc/pymee1.md
> ++ 0-4の数字から任意の数字を選ぶ
確かに。。。修正します！

2018-07-26 15:22 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +| 要素になっている| in | x in 1| xに1が含まれている|
指摘ありがとうございます！
「x in 1」で「xに1が含まれている」だと、「"123" in "1"」でもTrueになるように見えてしまいますね。
こちら誤りなので、下記案を使わさせていただきます！

> x in y で、xはyに含まれているか? とか…

2018-07-26 15:28 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +>>> if unsei == 0:
確かに、、、下記のような形はどうでしょうか。
ifの場合は、インタプリタの実行やめて

1. コードをひとまず完成させる
1. 一度動作を確認
1. ifの前にprint("数字：+ num)を記載
1. 何回か実行して数字と結果の比較をしてもらう

2018-07-26 15:29 UTC, sanoP1man commented on 1st/doc/pymee1.md
> ++ 今まで、箱を1つづつ用意し、その中に値を代入
そうですね、修正しました！

2018-07-26 15:31 UTC, sanoP1man commented on 1st/doc/pymee1.md
> ++ 大きな箱の中身は0から始まる番号が振られており、こちらを元に値を取り出すことが可能
ちょっと文章を詳しくしました！

2018-07-26 15:33 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +> リスト名[offset]
英語をカタカナにして、補足も追加しました！

2018-07-29 11:08 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +
確かに、２行から１行になっただけではピンと来ないかもしれないですね。
強調するためにスライドを分けました。

2018-07-29 11:11 UTC, sanoP1man commented on 1st/doc/pymee1.md
> ++ 定義した順番に表示されない
この部分修正しました。

2018-07-29 11:31 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +	+ 辞書、文字列
すみません、こちら私の誤りです。
スライド削除しました。

2018-07-29 11:35 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +unsei_key = random.choice(list(omikuji.keys()))
修正しました。

2018-07-29 15:14 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +unsei_key = random.choice(list(omikuji.keys()))
omikuji.keys()ですが、おみくじプログラムを改良する前に対話モードで動作を確認してもらうようにしました。

2018-07-29 15:16 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +unsei = random.choice(omikuji)
確かにそうですね。。。
動作確認をしよう！というスライドを追加して一時的に動作確認用のコードを追加するようにしました。

2018-07-29 15:17 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +if '吉' in unsei['all']:
結構前にif文を説明している部分があったので復習というか形でスライドを追加しました。

2018-07-29 15:17 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +print(name + 'さんの運勢は、' + unsei['all']+ '\n' + unsei['work'])
説明なしだったので、、、追加しました！

2018-07-29 15:20 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +```
時間見合いで省きましょうか。
省く場合は、「0-4の数字からランダムで選択するには、下記２行を追加します！ただし、importはファイルの最初。」ぐらいで説明します。

2018-07-29 15:28 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +# # coding: utf-8
ファイル作成の時点で注意喚起を追記しました

2018-07-29 15:38 UTC, sanoP1man commented on 1st/doc/pymee1.md
> ++ Bool(True, False)
Booleanに修正しました！

2018-07-29 15:39 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +変数名「name」を入力、もしくはpirnt(name)を実行して入力した名前が表示されることを確認
修正しました！

2018-07-29 15:55 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +	['大吉', '中吉', '小吉', '吉', '吉']
吉を削除、吉追加、再度削除の流れに修正しました！

2018-07-29 15:56 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +	print('こういう日もあります。元気出してくだい！！')
修正しました！

2018-07-29 15:58 UTC, sanoP1man commented on 1st/doc/pymee1.md
> ++ 「in」は「〜を含んでいる」という比較演算子
最初の方のまとめで、ifをやっていたので、まとめから無くした背景があります。
なので、こちらでは説明記載不要かなと思いました。

2018-07-29 16:10 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +	+ 型をしまう箱の種類
修正しました！

2018-07-29 16:18 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +>>> if unsei == 0:
#11 でissueあげてました！

2018-07-29 16:25 UTC, sanoP1man commented
指摘点を修正しました。8/3(金)までにレビューをお願いします。
それと、すみません、イメージ図を作ったほうがイメージつく部分(リストとか辞書とか)について絵を追加していなかったので別途イラストを追加すると思います。
イラスト部分考慮していなくてすみません。。。

2018-08-01 04:32 UTC, JinKanai requested changes
指摘ありなので、request changeします！

2018-08-01 04:32 UTC, JinKanai commented on 1st/doc/pymee1.md
> +     + コンパイルの時間が不要なため手間が少ない
実行までにかかる手間が少ない

2018-08-01 04:32 UTC, JinKanai commented on 1st/doc/pymee1.md
> +     + コンパイルの時間が不要なため手間が少ない
時間見合いですが、デメリットも載せたほうがいいかな・・・
- 実行速度が遅い

2018-08-01 04:32 UTC, JinKanai commented on 1st/doc/pymee1.md
> +
デメリット
- コンパイルの手間が必要
- 実行するハードウェアごとにコンパイルが必要（javaなど、必要ないように工夫してある言語もある）

2018-08-01 04:32 UTC, JinKanai commented on 1st/doc/pymee1.md
> ++ プログラミング言語って？
ここと、

2018-08-01 04:32 UTC, JinKanai commented on 1st/doc/pymee1.md
> +    - マシンに実行させる処理を書く言語
ここは、プログラミングって？　に移動したほうがいい気がする・・

2018-08-01 04:32 UTC, JinKanai commented on 1st/doc/pymee1.md
> +   **ここでフォルダのパスをメモして下さい**
フルパス　ですかね？

2018-08-01 04:32 UTC, JinKanai commented on 1st/doc/pymee1.md
> +<u>ファイルの文字コードは**「utf-8」** で保存して下さい！！</u>
windows ユーザー向け限定メッセージかな・・・
今時、EUCとかでlinux使ってる人はいないと信じたい。。。

サクラエディタとかでの保存方法ってみんな知ってるもんかしら。
現場で聞かれても運営側が即答できればOK

2018-08-01 04:32 UTC, JinKanai commented on 1st/doc/pymee1.md
> + + メリット: 変数の型をコンパイラが判定しなくていいため早い
早いのは、コーディングが早くなるってことですよね？
動作速度は遅くなります。

2018-08-01 04:32 UTC, JinKanai commented on 1st/doc/pymee1.md
> + + デメリット: 型宣言が面倒！
ん？　これは何に対するデメリットだ？静的言語のデメリット？

2018-08-02 15:37 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +   **ここでフォルダのパスをメモして下さい**
フルパスです！直します〜

2018-08-02 15:43 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +<u>ファイルの文字コードは**「utf-8」** で保存して下さい！！</u>
ここはwindowsユーザに向けてのメッセージになります。
サクラエディタは保存時に指定するプルダウンがあるのでそこで指定すれば大丈夫ですね！

もし、linuxユーザでutf-8でない人でviだったら下記方法で対応します！
https://qiita.com/tsukachin999/items/e59124dded66cf40559f

2018-08-02 15:46 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +    - マシンに実行させる処理を書く言語
確かに、、、python限定じゃないですもんね、、、
プログラミング部分に移動します！

2018-08-02 16:12 UTC, sanoP1man commented on 1st/doc/pymee1.md
> + + メリット: 変数の型をコンパイラが判定しなくていいため早い
すみません、こちら何を思ったか静的型付のことを記載してしまったと思います。

2018-08-02 16:12 UTC, sanoP1man commented on 1st/doc/pymee1.md
> + + デメリット: 型宣言が面倒！
すみません、こちら何を思ったか静的型付のことを記載してしまったと思います。
こっちもです。。。

2018-08-02 16:34 UTC, sanoP1man commented on 1st/doc/pymee1.md
> +     + コンパイルの時間が不要なため手間が少ない
実行環境についてはデメリットも記載しました〜

2018-08-03 23:42 UTC, JinKanai approved these changes
一箇所、気になることがありましたが修正はおまかせします。承認！

2018-08-03 23:42 UTC, JinKanai commented on 1st/doc/pymee1.md
> + + メリット: 型の宣言を行う必要がないためプログラムを書く手間が省ける
細かい指摘で恐縮だけど、「プログラムを書く手間が省ける」だとプログラムを書かなくてもよい、という意味にも取れるので（おれだけ？）、プログラミングにかける時間が少なくて済むことが多い、といった記述のほうがいいかと・・・

2018-08-05 12:20 UTC, sanoP1man commented on 1st/doc/pymee1.md
> + + メリット: 型の宣言を行う必要がないためプログラムを書く手間が省ける
難しいですね。。。
確かにそうも取れてしまいますね。。。
こちら修正しました！

2018-08-13 04:19 UTC, JinKanai commented
おみくじに仕事運を追加しよう　の最初の絵、リストのインデックスがふたつとも０になってるけどこれはOK？

2018-08-15 10:36 UTC, juke211 approved these changes

2018-08-20 01:20 UTC, sanoP1man commented
画像修正しました！
こちらで、資料を本流にマージします。

2018-08-20 01:26 UTC, JinKanai commented
了解です、本来は全員のapproveが必要ですが、しょうがないすね・・・

2018-08-20 16:22 UTC, sanoP1man commented
すみません、、、資料を見返していたらフォーマットが崩れていたので修正しました。
それと、プログラミングとはの部分について画像追加しました。
こちらでマージします！

2018-08-21 07:39 UTC, closed without merging